# This file is part of the Spectrum +4 Project.
# Licencing information can be found in the LICENCE file
# (C) 2019 Spectrum +4 Authors. All rights reserved.

# This file is auto-generated by all.sh. DO NOT EDIT!

.set SYSVAR_COUNT, 58                   // number of system variables
.set SYSVAR_MASK_BYTES, 16              // number of bytes required to store enough
                                        // 64 bit bitmasks to mask all sysvars

.data


.align 3
sysvars_meta:
  .quad sysvar_COL
  .quad sysvar_WIDTH
  .quad sysvar_TVPARS
  .quad sysvar_RASP
  .quad sysvar_PIP
  .quad sysvar_FLAGS
  .quad sysvar_FLAGS2
  .quad sysvar_TV_FLAG
  .quad sysvar_BORDCR
  .quad sysvar_ERR_NR
  .quad sysvar_DF_SZ
  .quad sysvar_SCR_CT
  .quad sysvar_P_POSN
  .quad sysvar_ECHO_E_COL
  .quad sysvar_ECHO_E_ROW
  .quad sysvar_S_POSN_COL
  .quad sysvar_S_POSN_ROW
  .quad sysvar_S_POSNL_COL
  .quad sysvar_S_POSNL_ROW
  .quad sysvar_P_FLAG
  .quad sysvar_BREG
  .quad sysvar_REPDEL
  .quad sysvar_REPPER
  .quad sysvar_ATTR_P
  .quad sysvar_MASK_P
  .quad sysvar_ATTR_T
  .quad sysvar_MASK_T
  .quad sysvar_BAUD
  .quad sysvar_SERFL
  .quad sysvar_RNFIRST
  .quad sysvar_RNSTEP
  .quad sysvar_STRMS
  .quad sysvar_COORDS
  .quad sysvar_COORDS_Y
  .quad sysvar_TVDATA
  .quad sysvar_SFNEXT
  .quad sysvar_SFSPACE
  .quad sysvar_CHARS
  .quad sysvar_LIST_SP
  .quad sysvar_VARS
  .quad sysvar_CHANS
  .quad sysvar_CURCHL
  .quad sysvar_PROG
  .quad sysvar_DATADD
  .quad sysvar_E_LINE
  .quad sysvar_CH_ADD
  .quad sysvar_X_PTR
  .quad sysvar_WORKSP
  .quad sysvar_STKBOT
  .quad sysvar_STKEND
  .quad sysvar_RAMTOP
  .quad sysvar_P_RAMT
  .quad sysvar_UDG
  .quad sysvar_ERR_SP
  .quad sysvar_DF_CC
  .quad sysvar_DF_CCL
  .quad sysvar_PR_CC
  .quad sysvar_MEMBOT


.align 3
sysvar_COL:
  .quad COL-sysvars                       // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "COL"                            // name


.align 3
sysvar_WIDTH:
  .quad WIDTH-sysvars                     // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "WIDTH"                          // name


.align 3
sysvar_TVPARS:
  .quad TVPARS-sysvars                    // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "TVPARS"                         // name


.align 3
sysvar_RASP:
  .quad RASP-sysvars                      // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "RASP"                           // name


.align 3
sysvar_PIP:
  .quad PIP-sysvars                       // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "PIP"                            // name


.align 3
sysvar_FLAGS:
  .quad FLAGS-sysvars                     // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "FLAGS"                          // name


.align 3
sysvar_FLAGS2:
  .quad FLAGS2-sysvars                    // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "FLAGS2"                         // name


.align 3
sysvar_TV_FLAG:
  .quad TV_FLAG-sysvars                   // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "TV_FLAG"                        // name


.align 3
sysvar_BORDCR:
  .quad BORDCR-sysvars                    // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "BORDCR"                         // name


.align 3
sysvar_ERR_NR:
  .quad ERR_NR-sysvars                    // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "ERR_NR"                         // name


.align 3
sysvar_DF_SZ:
  .quad DF_SZ-sysvars                     // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "DF_SZ"                          // name


.align 3
sysvar_SCR_CT:
  .quad SCR_CT-sysvars                    // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "SCR_CT"                         // name


.align 3
sysvar_P_POSN:
  .quad P_POSN-sysvars                    // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "P_POSN"                         // name


.align 3
sysvar_ECHO_E_COL:
  .quad ECHO_E_COL-sysvars                // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "ECHO_E_COL"                     // name


.align 3
sysvar_ECHO_E_ROW:
  .quad ECHO_E_ROW-sysvars                // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "ECHO_E_ROW"                     // name


.align 3
sysvar_S_POSN_COL:
  .quad S_POSN_COL-sysvars                // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "S_POSN_COL"                     // name


.align 3
sysvar_S_POSN_ROW:
  .quad S_POSN_ROW-sysvars                // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "S_POSN_ROW"                     // name


.align 3
sysvar_S_POSNL_COL:
  .quad S_POSNL_COL-sysvars               // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "S_POSNL_COL"                    // name


.align 3
sysvar_S_POSNL_ROW:
  .quad S_POSNL_ROW-sysvars               // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "S_POSNL_ROW"                    // name


.align 3
sysvar_P_FLAG:
  .quad P_FLAG-sysvars                    // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "P_FLAG"                         // name


.align 3
sysvar_BREG:
  .quad BREG-sysvars                      // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "BREG"                           // name


.align 3
sysvar_REPDEL:
  .quad REPDEL-sysvars                    // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "REPDEL"                         // name


.align 3
sysvar_REPPER:
  .quad REPPER-sysvars                    // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "REPPER"                         // name


.align 3
sysvar_ATTR_P:
  .quad ATTR_P-sysvars                    // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "ATTR_P"                         // name


.align 3
sysvar_MASK_P:
  .quad MASK_P-sysvars                    // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "MASK_P"                         // name


.align 3
sysvar_ATTR_T:
  .quad ATTR_T-sysvars                    // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "ATTR_T"                         // name


.align 3
sysvar_MASK_T:
  .quad MASK_T-sysvars                    // sysvar address offset
  .byte 1                                 // size in bytes
  .asciz "MASK_T"                         // name


.align 3
sysvar_BAUD:
  .quad BAUD-sysvars                      // sysvar address offset
  .byte 2                                 // size in bytes
  .asciz "BAUD"                           // name


.align 3
sysvar_SERFL:
  .quad SERFL-sysvars                     // sysvar address offset
  .byte 2                                 // size in bytes
  .asciz "SERFL"                          // name


.align 3
sysvar_RNFIRST:
  .quad RNFIRST-sysvars                   // sysvar address offset
  .byte 2                                 // size in bytes
  .asciz "RNFIRST"                        // name


.align 3
sysvar_RNSTEP:
  .quad RNSTEP-sysvars                    // sysvar address offset
  .byte 2                                 // size in bytes
  .asciz "RNSTEP"                         // name


.align 3
sysvar_STRMS:
  .quad STRMS-sysvars                     // sysvar address offset
  .byte 2*19                              // size in bytes
  .asciz "STRMS"                          // name


.align 3
sysvar_COORDS:
  .quad COORDS-sysvars                    // sysvar address offset
  .byte 2                                 // size in bytes
  .asciz "COORDS"                         // name


.align 3
sysvar_COORDS_Y:
  .quad COORDS_Y-sysvars                  // sysvar address offset
  .byte 2                                 // size in bytes
  .asciz "COORDS_Y"                       // name


.align 3
sysvar_TVDATA:
  .quad TVDATA-sysvars                    // sysvar address offset
  .byte 2                                 // size in bytes
  .asciz "TVDATA"                         // name


.align 3
sysvar_SFNEXT:
  .quad SFNEXT-sysvars                    // sysvar address offset
  .byte 8                                 // size in bytes
  .asciz "SFNEXT"                         // name


.align 3
sysvar_SFSPACE:
  .quad SFSPACE-sysvars                   // sysvar address offset
  .byte 8                                 // size in bytes
  .asciz "SFSPACE"                        // name


.align 3
sysvar_CHARS:
  .quad CHARS-sysvars                     // sysvar address offset
  .byte 8                                 // size in bytes
  .asciz "CHARS"                          // name


.align 3
sysvar_LIST_SP:
  .quad LIST_SP-sysvars                   // sysvar address offset
  .byte 8                                 // size in bytes
  .asciz "LIST_SP"                        // name


.align 3
sysvar_VARS:
  .quad VARS-sysvars                      // sysvar address offset
  .byte 8                                 // size in bytes
  .asciz "VARS"                           // name


.align 3
sysvar_CHANS:
  .quad CHANS-sysvars                     // sysvar address offset
  .byte 8                                 // size in bytes
  .asciz "CHANS"                          // name


.align 3
sysvar_CURCHL:
  .quad CURCHL-sysvars                    // sysvar address offset
  .byte 8                                 // size in bytes
  .asciz "CURCHL"                         // name


.align 3
sysvar_PROG:
  .quad PROG-sysvars                      // sysvar address offset
  .byte 8                                 // size in bytes
  .asciz "PROG"                           // name


.align 3
sysvar_DATADD:
  .quad DATADD-sysvars                    // sysvar address offset
  .byte 8                                 // size in bytes
  .asciz "DATADD"                         // name


.align 3
sysvar_E_LINE:
  .quad E_LINE-sysvars                    // sysvar address offset
  .byte 8                                 // size in bytes
  .asciz "E_LINE"                         // name


.align 3
sysvar_CH_ADD:
  .quad CH_ADD-sysvars                    // sysvar address offset
  .byte 8                                 // size in bytes
  .asciz "CH_ADD"                         // name


.align 3
sysvar_X_PTR:
  .quad X_PTR-sysvars                     // sysvar address offset
  .byte 8                                 // size in bytes
  .asciz "X_PTR"                          // name


.align 3
sysvar_WORKSP:
  .quad WORKSP-sysvars                    // sysvar address offset
  .byte 8                                 // size in bytes
  .asciz "WORKSP"                         // name


.align 3
sysvar_STKBOT:
  .quad STKBOT-sysvars                    // sysvar address offset
  .byte 8                                 // size in bytes
  .asciz "STKBOT"                         // name


.align 3
sysvar_STKEND:
  .quad STKEND-sysvars                    // sysvar address offset
  .byte 8                                 // size in bytes
  .asciz "STKEND"                         // name


.align 3
sysvar_RAMTOP:
  .quad RAMTOP-sysvars                    // sysvar address offset
  .byte 8                                 // size in bytes
  .asciz "RAMTOP"                         // name


.align 3
sysvar_P_RAMT:
  .quad P_RAMT-sysvars                    // sysvar address offset
  .byte 8                                 // size in bytes
  .asciz "P_RAMT"                         // name


.align 3
sysvar_UDG:
  .quad UDG-sysvars                       // sysvar address offset
  .byte 8                                 // size in bytes
  .asciz "UDG"                            // name


.align 3
sysvar_ERR_SP:
  .quad ERR_SP-sysvars                    // sysvar address offset
  .byte 8                                 // size in bytes
  .asciz "ERR_SP"                         // name


.align 3
sysvar_DF_CC:
  .quad DF_CC-sysvars                     // sysvar address offset
  .byte 8                                 // size in bytes
  .asciz "DF_CC"                          // name


.align 3
sysvar_DF_CCL:
  .quad DF_CCL-sysvars                    // sysvar address offset
  .byte 8                                 // size in bytes
  .asciz "DF_CCL"                         // name


.align 3
sysvar_PR_CC:
  .quad PR_CC-sysvars                     // sysvar address offset
  .byte 8                                 // size in bytes
  .asciz "PR_CC"                          // name


.align 3
sysvar_MEMBOT:
  .quad MEMBOT-sysvars                    // sysvar address offset
  .byte 32                                // size in bytes
  .asciz "MEMBOT"                         // name
