# This file is part of the Spectrum +4 Project.
# Licencing information can be found in the LICENCE file
# (C) 2021 Spectrum +4 Authors. All rights reserved.

# This file is auto-generated by test_cl_set.sh. DO NOT EDIT!

.text


cl_set_lower_screen_01_18_01_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x01, DF_SZ
  ret

cl_set_lower_screen_01_18_01_setup_regs:
  ld      bc, 0x1801
  ret

cl_set_lower_screen_01_18_01_effects:
  _strh   0x1801, S_POSN_X_L
  _strh   0x1801, ECHO_E_X
  _strh   0x5100, DF_CC_L
  ret

cl_set_lower_screen_01_18_01_effects_regs:
  ld      a, 0x20
  ld      de, 0x20
  ld      hl, 0x5100
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_01_0d_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_01_0d_0c_setup_regs:
  ld      bc, 0x0d01
  ret

cl_set_lower_screen_01_0d_0c_effects:
  _strh   0x0d01, S_POSN_X_L
  _strh   0x0d01, ECHO_E_X
  _strh   0x5100, DF_CC_L
  ret

cl_set_lower_screen_01_0d_0c_effects_regs:
  ld      a, 0x20
  ld      de, 0x20
  ld      hl, 0x5100
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_01_10_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_01_10_0c_setup_regs:
  ld      bc, 0x1001
  ret

cl_set_lower_screen_01_10_0c_effects:
  _strh   0x1001, S_POSN_X_L
  _strh   0x1001, ECHO_E_X
  _strh   0x50a0, DF_CC_L
  ret

cl_set_lower_screen_01_10_0c_effects_regs:
  ld      a, 0x20
  ld      de, 0x20
  ld      hl, 0x50a0
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_01_13_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_01_13_0c_setup_regs:
  ld      bc, 0x1301
  ret

cl_set_lower_screen_01_13_0c_effects:
  _strh   0x1301, S_POSN_X_L
  _strh   0x1301, ECHO_E_X
  _strh   0x5040, DF_CC_L
  ret

cl_set_lower_screen_01_13_0c_effects_regs:
  ld      a, 0x20
  ld      de, 0x20
  ld      hl, 0x5040
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_01_16_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_01_16_0c_setup_regs:
  ld      bc, 0x1601
  ret

cl_set_lower_screen_01_16_0c_effects:
  _strh   0x1601, S_POSN_X_L
  _strh   0x1601, ECHO_E_X
  _strh   0x48e0, DF_CC_L
  ret

cl_set_lower_screen_01_16_0c_effects_regs:
  ld      a, 0x20
  ld      de, 0x20
  ld      hl, 0x48e0
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_01_06_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_01_06_13_setup_regs:
  ld      bc, 0x0601
  ret

cl_set_lower_screen_01_06_13_effects:
  _strh   0x0601, S_POSN_X_L
  _strh   0x0601, ECHO_E_X
  _strh   0x5100, DF_CC_L
  ret

cl_set_lower_screen_01_06_13_effects_regs:
  ld      a, 0x20
  ld      de, 0x20
  ld      hl, 0x5100
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_01_09_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_01_09_13_setup_regs:
  ld      bc, 0x0901
  ret

cl_set_lower_screen_01_09_13_effects:
  _strh   0x0901, S_POSN_X_L
  _strh   0x0901, ECHO_E_X
  _strh   0x50a0, DF_CC_L
  ret

cl_set_lower_screen_01_09_13_effects_regs:
  ld      a, 0x20
  ld      de, 0x20
  ld      hl, 0x50a0
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_01_0c_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_01_0c_13_setup_regs:
  ld      bc, 0x0c01
  ret

cl_set_lower_screen_01_0c_13_effects:
  _strh   0x0c01, S_POSN_X_L
  _strh   0x0c01, ECHO_E_X
  _strh   0x5040, DF_CC_L
  ret

cl_set_lower_screen_01_0c_13_effects_regs:
  ld      a, 0x20
  ld      de, 0x20
  ld      hl, 0x5040
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_01_0f_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_01_0f_13_setup_regs:
  ld      bc, 0x0f01
  ret

cl_set_lower_screen_01_0f_13_effects:
  _strh   0x0f01, S_POSN_X_L
  _strh   0x0f01, ECHO_E_X
  _strh   0x48e0, DF_CC_L
  ret

cl_set_lower_screen_01_0f_13_effects_regs:
  ld      a, 0x20
  ld      de, 0x20
  ld      hl, 0x48e0
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_01_12_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_01_12_13_setup_regs:
  ld      bc, 0x1201
  ret

cl_set_lower_screen_01_12_13_effects:
  _strh   0x1201, S_POSN_X_L
  _strh   0x1201, ECHO_E_X
  _strh   0x4880, DF_CC_L
  ret

cl_set_lower_screen_01_12_13_effects_regs:
  ld      a, 0x20
  ld      de, 0x20
  ld      hl, 0x4880
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_01_15_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_01_15_13_setup_regs:
  ld      bc, 0x1501
  ret

cl_set_lower_screen_01_15_13_effects:
  _strh   0x1501, S_POSN_X_L
  _strh   0x1501, ECHO_E_X
  _strh   0x4820, DF_CC_L
  ret

cl_set_lower_screen_01_15_13_effects_regs:
  ld      a, 0x20
  ld      de, 0x20
  ld      hl, 0x4820
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_01_18_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_01_18_13_setup_regs:
  ld      bc, 0x1801
  ret

cl_set_lower_screen_01_18_13_effects:
  _strh   0x1801, S_POSN_X_L
  _strh   0x1801, ECHO_E_X
  _strh   0x40c0, DF_CC_L
  ret

cl_set_lower_screen_01_18_13_effects_regs:
  ld      a, 0x20
  ld      de, 0x20
  ld      hl, 0x40c0
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_01_01_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_01_01_18_setup_regs:
  ld      bc, 0x0101
  ret

cl_set_lower_screen_01_01_18_effects:
  _strh   0x0101, S_POSN_X_L
  _strh   0x0101, ECHO_E_X
  _strh   0x5100, DF_CC_L
  ret

cl_set_lower_screen_01_01_18_effects_regs:
  ld      a, 0x20
  ld      de, 0x20
  ld      hl, 0x5100
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_01_04_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_01_04_18_setup_regs:
  ld      bc, 0x0401
  ret

cl_set_lower_screen_01_04_18_effects:
  _strh   0x0401, S_POSN_X_L
  _strh   0x0401, ECHO_E_X
  _strh   0x50a0, DF_CC_L
  ret

cl_set_lower_screen_01_04_18_effects_regs:
  ld      a, 0x20
  ld      de, 0x20
  ld      hl, 0x50a0
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_01_07_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_01_07_18_setup_regs:
  ld      bc, 0x0701
  ret

cl_set_lower_screen_01_07_18_effects:
  _strh   0x0701, S_POSN_X_L
  _strh   0x0701, ECHO_E_X
  _strh   0x5040, DF_CC_L
  ret

cl_set_lower_screen_01_07_18_effects_regs:
  ld      a, 0x20
  ld      de, 0x20
  ld      hl, 0x5040
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_01_0a_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_01_0a_18_setup_regs:
  ld      bc, 0x0a01
  ret

cl_set_lower_screen_01_0a_18_effects:
  _strh   0x0a01, S_POSN_X_L
  _strh   0x0a01, ECHO_E_X
  _strh   0x48e0, DF_CC_L
  ret

cl_set_lower_screen_01_0a_18_effects_regs:
  ld      a, 0x20
  ld      de, 0x20
  ld      hl, 0x48e0
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_01_0d_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_01_0d_18_setup_regs:
  ld      bc, 0x0d01
  ret

cl_set_lower_screen_01_0d_18_effects:
  _strh   0x0d01, S_POSN_X_L
  _strh   0x0d01, ECHO_E_X
  _strh   0x4880, DF_CC_L
  ret

cl_set_lower_screen_01_0d_18_effects_regs:
  ld      a, 0x20
  ld      de, 0x20
  ld      hl, 0x4880
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_01_10_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_01_10_18_setup_regs:
  ld      bc, 0x1001
  ret

cl_set_lower_screen_01_10_18_effects:
  _strh   0x1001, S_POSN_X_L
  _strh   0x1001, ECHO_E_X
  _strh   0x4820, DF_CC_L
  ret

cl_set_lower_screen_01_10_18_effects_regs:
  ld      a, 0x20
  ld      de, 0x20
  ld      hl, 0x4820
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_01_13_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_01_13_18_setup_regs:
  ld      bc, 0x1301
  ret

cl_set_lower_screen_01_13_18_effects:
  _strh   0x1301, S_POSN_X_L
  _strh   0x1301, ECHO_E_X
  _strh   0x40c0, DF_CC_L
  ret

cl_set_lower_screen_01_13_18_effects_regs:
  ld      a, 0x20
  ld      de, 0x20
  ld      hl, 0x40c0
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_01_16_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_01_16_18_setup_regs:
  ld      bc, 0x1601
  ret

cl_set_lower_screen_01_16_18_effects:
  _strh   0x1601, S_POSN_X_L
  _strh   0x1601, ECHO_E_X
  _strh   0x4060, DF_CC_L
  ret

cl_set_lower_screen_01_16_18_effects_regs:
  ld      a, 0x20
  ld      de, 0x20
  ld      hl, 0x4060
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_05_18_01_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x01, DF_SZ
  ret

cl_set_lower_screen_05_18_01_setup_regs:
  ld      bc, 0x1805
  ret

cl_set_lower_screen_05_18_01_effects:
  _strh   0x1805, S_POSN_X_L
  _strh   0x1805, ECHO_E_X
  _strh   0x50fc, DF_CC_L
  ret

cl_set_lower_screen_05_18_01_effects_regs:
  ld      a, 0x1c
  ld      de, 0x1c
  ld      hl, 0x50fc
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_05_0d_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_05_0d_0c_setup_regs:
  ld      bc, 0x0d05
  ret

cl_set_lower_screen_05_0d_0c_effects:
  _strh   0x0d05, S_POSN_X_L
  _strh   0x0d05, ECHO_E_X
  _strh   0x50fc, DF_CC_L
  ret

cl_set_lower_screen_05_0d_0c_effects_regs:
  ld      a, 0x1c
  ld      de, 0x1c
  ld      hl, 0x50fc
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_05_10_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_05_10_0c_setup_regs:
  ld      bc, 0x1005
  ret

cl_set_lower_screen_05_10_0c_effects:
  _strh   0x1005, S_POSN_X_L
  _strh   0x1005, ECHO_E_X
  _strh   0x509c, DF_CC_L
  ret

cl_set_lower_screen_05_10_0c_effects_regs:
  ld      a, 0x1c
  ld      de, 0x1c
  ld      hl, 0x509c
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_05_13_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_05_13_0c_setup_regs:
  ld      bc, 0x1305
  ret

cl_set_lower_screen_05_13_0c_effects:
  _strh   0x1305, S_POSN_X_L
  _strh   0x1305, ECHO_E_X
  _strh   0x503c, DF_CC_L
  ret

cl_set_lower_screen_05_13_0c_effects_regs:
  ld      a, 0x1c
  ld      de, 0x1c
  ld      hl, 0x503c
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_05_16_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_05_16_0c_setup_regs:
  ld      bc, 0x1605
  ret

cl_set_lower_screen_05_16_0c_effects:
  _strh   0x1605, S_POSN_X_L
  _strh   0x1605, ECHO_E_X
  _strh   0x48dc, DF_CC_L
  ret

cl_set_lower_screen_05_16_0c_effects_regs:
  ld      a, 0x1c
  ld      de, 0x1c
  ld      hl, 0x48dc
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_05_06_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_05_06_13_setup_regs:
  ld      bc, 0x0605
  ret

cl_set_lower_screen_05_06_13_effects:
  _strh   0x0605, S_POSN_X_L
  _strh   0x0605, ECHO_E_X
  _strh   0x50fc, DF_CC_L
  ret

cl_set_lower_screen_05_06_13_effects_regs:
  ld      a, 0x1c
  ld      de, 0x1c
  ld      hl, 0x50fc
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_05_09_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_05_09_13_setup_regs:
  ld      bc, 0x0905
  ret

cl_set_lower_screen_05_09_13_effects:
  _strh   0x0905, S_POSN_X_L
  _strh   0x0905, ECHO_E_X
  _strh   0x509c, DF_CC_L
  ret

cl_set_lower_screen_05_09_13_effects_regs:
  ld      a, 0x1c
  ld      de, 0x1c
  ld      hl, 0x509c
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_05_0c_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_05_0c_13_setup_regs:
  ld      bc, 0x0c05
  ret

cl_set_lower_screen_05_0c_13_effects:
  _strh   0x0c05, S_POSN_X_L
  _strh   0x0c05, ECHO_E_X
  _strh   0x503c, DF_CC_L
  ret

cl_set_lower_screen_05_0c_13_effects_regs:
  ld      a, 0x1c
  ld      de, 0x1c
  ld      hl, 0x503c
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_05_0f_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_05_0f_13_setup_regs:
  ld      bc, 0x0f05
  ret

cl_set_lower_screen_05_0f_13_effects:
  _strh   0x0f05, S_POSN_X_L
  _strh   0x0f05, ECHO_E_X
  _strh   0x48dc, DF_CC_L
  ret

cl_set_lower_screen_05_0f_13_effects_regs:
  ld      a, 0x1c
  ld      de, 0x1c
  ld      hl, 0x48dc
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_05_12_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_05_12_13_setup_regs:
  ld      bc, 0x1205
  ret

cl_set_lower_screen_05_12_13_effects:
  _strh   0x1205, S_POSN_X_L
  _strh   0x1205, ECHO_E_X
  _strh   0x487c, DF_CC_L
  ret

cl_set_lower_screen_05_12_13_effects_regs:
  ld      a, 0x1c
  ld      de, 0x1c
  ld      hl, 0x487c
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_05_15_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_05_15_13_setup_regs:
  ld      bc, 0x1505
  ret

cl_set_lower_screen_05_15_13_effects:
  _strh   0x1505, S_POSN_X_L
  _strh   0x1505, ECHO_E_X
  _strh   0x481c, DF_CC_L
  ret

cl_set_lower_screen_05_15_13_effects_regs:
  ld      a, 0x1c
  ld      de, 0x1c
  ld      hl, 0x481c
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_05_18_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_05_18_13_setup_regs:
  ld      bc, 0x1805
  ret

cl_set_lower_screen_05_18_13_effects:
  _strh   0x1805, S_POSN_X_L
  _strh   0x1805, ECHO_E_X
  _strh   0x40bc, DF_CC_L
  ret

cl_set_lower_screen_05_18_13_effects_regs:
  ld      a, 0x1c
  ld      de, 0x1c
  ld      hl, 0x40bc
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_05_01_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_05_01_18_setup_regs:
  ld      bc, 0x0105
  ret

cl_set_lower_screen_05_01_18_effects:
  _strh   0x0105, S_POSN_X_L
  _strh   0x0105, ECHO_E_X
  _strh   0x50fc, DF_CC_L
  ret

cl_set_lower_screen_05_01_18_effects_regs:
  ld      a, 0x1c
  ld      de, 0x1c
  ld      hl, 0x50fc
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_05_04_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_05_04_18_setup_regs:
  ld      bc, 0x0405
  ret

cl_set_lower_screen_05_04_18_effects:
  _strh   0x0405, S_POSN_X_L
  _strh   0x0405, ECHO_E_X
  _strh   0x509c, DF_CC_L
  ret

cl_set_lower_screen_05_04_18_effects_regs:
  ld      a, 0x1c
  ld      de, 0x1c
  ld      hl, 0x509c
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_05_07_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_05_07_18_setup_regs:
  ld      bc, 0x0705
  ret

cl_set_lower_screen_05_07_18_effects:
  _strh   0x0705, S_POSN_X_L
  _strh   0x0705, ECHO_E_X
  _strh   0x503c, DF_CC_L
  ret

cl_set_lower_screen_05_07_18_effects_regs:
  ld      a, 0x1c
  ld      de, 0x1c
  ld      hl, 0x503c
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_05_0a_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_05_0a_18_setup_regs:
  ld      bc, 0x0a05
  ret

cl_set_lower_screen_05_0a_18_effects:
  _strh   0x0a05, S_POSN_X_L
  _strh   0x0a05, ECHO_E_X
  _strh   0x48dc, DF_CC_L
  ret

cl_set_lower_screen_05_0a_18_effects_regs:
  ld      a, 0x1c
  ld      de, 0x1c
  ld      hl, 0x48dc
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_05_0d_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_05_0d_18_setup_regs:
  ld      bc, 0x0d05
  ret

cl_set_lower_screen_05_0d_18_effects:
  _strh   0x0d05, S_POSN_X_L
  _strh   0x0d05, ECHO_E_X
  _strh   0x487c, DF_CC_L
  ret

cl_set_lower_screen_05_0d_18_effects_regs:
  ld      a, 0x1c
  ld      de, 0x1c
  ld      hl, 0x487c
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_05_10_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_05_10_18_setup_regs:
  ld      bc, 0x1005
  ret

cl_set_lower_screen_05_10_18_effects:
  _strh   0x1005, S_POSN_X_L
  _strh   0x1005, ECHO_E_X
  _strh   0x481c, DF_CC_L
  ret

cl_set_lower_screen_05_10_18_effects_regs:
  ld      a, 0x1c
  ld      de, 0x1c
  ld      hl, 0x481c
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_05_13_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_05_13_18_setup_regs:
  ld      bc, 0x1305
  ret

cl_set_lower_screen_05_13_18_effects:
  _strh   0x1305, S_POSN_X_L
  _strh   0x1305, ECHO_E_X
  _strh   0x40bc, DF_CC_L
  ret

cl_set_lower_screen_05_13_18_effects_regs:
  ld      a, 0x1c
  ld      de, 0x1c
  ld      hl, 0x40bc
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_05_16_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_05_16_18_setup_regs:
  ld      bc, 0x1605
  ret

cl_set_lower_screen_05_16_18_effects:
  _strh   0x1605, S_POSN_X_L
  _strh   0x1605, ECHO_E_X
  _strh   0x405c, DF_CC_L
  ret

cl_set_lower_screen_05_16_18_effects_regs:
  ld      a, 0x1c
  ld      de, 0x1c
  ld      hl, 0x405c
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_0d_18_01_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x01, DF_SZ
  ret

cl_set_lower_screen_0d_18_01_setup_regs:
  ld      bc, 0x180d
  ret

cl_set_lower_screen_0d_18_01_effects:
  _strh   0x180d, S_POSN_X_L
  _strh   0x180d, ECHO_E_X
  _strh   0x50f4, DF_CC_L
  ret

cl_set_lower_screen_0d_18_01_effects_regs:
  ld      a, 0x14
  ld      de, 0x14
  ld      hl, 0x50f4
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_0d_0d_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_0d_0d_0c_setup_regs:
  ld      bc, 0x0d0d
  ret

cl_set_lower_screen_0d_0d_0c_effects:
  _strh   0x0d0d, S_POSN_X_L
  _strh   0x0d0d, ECHO_E_X
  _strh   0x50f4, DF_CC_L
  ret

cl_set_lower_screen_0d_0d_0c_effects_regs:
  ld      a, 0x14
  ld      de, 0x14
  ld      hl, 0x50f4
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_0d_10_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_0d_10_0c_setup_regs:
  ld      bc, 0x100d
  ret

cl_set_lower_screen_0d_10_0c_effects:
  _strh   0x100d, S_POSN_X_L
  _strh   0x100d, ECHO_E_X
  _strh   0x5094, DF_CC_L
  ret

cl_set_lower_screen_0d_10_0c_effects_regs:
  ld      a, 0x14
  ld      de, 0x14
  ld      hl, 0x5094
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_0d_13_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_0d_13_0c_setup_regs:
  ld      bc, 0x130d
  ret

cl_set_lower_screen_0d_13_0c_effects:
  _strh   0x130d, S_POSN_X_L
  _strh   0x130d, ECHO_E_X
  _strh   0x5034, DF_CC_L
  ret

cl_set_lower_screen_0d_13_0c_effects_regs:
  ld      a, 0x14
  ld      de, 0x14
  ld      hl, 0x5034
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_0d_16_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_0d_16_0c_setup_regs:
  ld      bc, 0x160d
  ret

cl_set_lower_screen_0d_16_0c_effects:
  _strh   0x160d, S_POSN_X_L
  _strh   0x160d, ECHO_E_X
  _strh   0x48d4, DF_CC_L
  ret

cl_set_lower_screen_0d_16_0c_effects_regs:
  ld      a, 0x14
  ld      de, 0x14
  ld      hl, 0x48d4
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_0d_06_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_0d_06_13_setup_regs:
  ld      bc, 0x060d
  ret

cl_set_lower_screen_0d_06_13_effects:
  _strh   0x060d, S_POSN_X_L
  _strh   0x060d, ECHO_E_X
  _strh   0x50f4, DF_CC_L
  ret

cl_set_lower_screen_0d_06_13_effects_regs:
  ld      a, 0x14
  ld      de, 0x14
  ld      hl, 0x50f4
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_0d_09_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_0d_09_13_setup_regs:
  ld      bc, 0x090d
  ret

cl_set_lower_screen_0d_09_13_effects:
  _strh   0x090d, S_POSN_X_L
  _strh   0x090d, ECHO_E_X
  _strh   0x5094, DF_CC_L
  ret

cl_set_lower_screen_0d_09_13_effects_regs:
  ld      a, 0x14
  ld      de, 0x14
  ld      hl, 0x5094
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_0d_0c_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_0d_0c_13_setup_regs:
  ld      bc, 0x0c0d
  ret

cl_set_lower_screen_0d_0c_13_effects:
  _strh   0x0c0d, S_POSN_X_L
  _strh   0x0c0d, ECHO_E_X
  _strh   0x5034, DF_CC_L
  ret

cl_set_lower_screen_0d_0c_13_effects_regs:
  ld      a, 0x14
  ld      de, 0x14
  ld      hl, 0x5034
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_0d_0f_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_0d_0f_13_setup_regs:
  ld      bc, 0x0f0d
  ret

cl_set_lower_screen_0d_0f_13_effects:
  _strh   0x0f0d, S_POSN_X_L
  _strh   0x0f0d, ECHO_E_X
  _strh   0x48d4, DF_CC_L
  ret

cl_set_lower_screen_0d_0f_13_effects_regs:
  ld      a, 0x14
  ld      de, 0x14
  ld      hl, 0x48d4
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_0d_12_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_0d_12_13_setup_regs:
  ld      bc, 0x120d
  ret

cl_set_lower_screen_0d_12_13_effects:
  _strh   0x120d, S_POSN_X_L
  _strh   0x120d, ECHO_E_X
  _strh   0x4874, DF_CC_L
  ret

cl_set_lower_screen_0d_12_13_effects_regs:
  ld      a, 0x14
  ld      de, 0x14
  ld      hl, 0x4874
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_0d_15_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_0d_15_13_setup_regs:
  ld      bc, 0x150d
  ret

cl_set_lower_screen_0d_15_13_effects:
  _strh   0x150d, S_POSN_X_L
  _strh   0x150d, ECHO_E_X
  _strh   0x4814, DF_CC_L
  ret

cl_set_lower_screen_0d_15_13_effects_regs:
  ld      a, 0x14
  ld      de, 0x14
  ld      hl, 0x4814
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_0d_18_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_0d_18_13_setup_regs:
  ld      bc, 0x180d
  ret

cl_set_lower_screen_0d_18_13_effects:
  _strh   0x180d, S_POSN_X_L
  _strh   0x180d, ECHO_E_X
  _strh   0x40b4, DF_CC_L
  ret

cl_set_lower_screen_0d_18_13_effects_regs:
  ld      a, 0x14
  ld      de, 0x14
  ld      hl, 0x40b4
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_0d_01_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_0d_01_18_setup_regs:
  ld      bc, 0x010d
  ret

cl_set_lower_screen_0d_01_18_effects:
  _strh   0x010d, S_POSN_X_L
  _strh   0x010d, ECHO_E_X
  _strh   0x50f4, DF_CC_L
  ret

cl_set_lower_screen_0d_01_18_effects_regs:
  ld      a, 0x14
  ld      de, 0x14
  ld      hl, 0x50f4
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_0d_04_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_0d_04_18_setup_regs:
  ld      bc, 0x040d
  ret

cl_set_lower_screen_0d_04_18_effects:
  _strh   0x040d, S_POSN_X_L
  _strh   0x040d, ECHO_E_X
  _strh   0x5094, DF_CC_L
  ret

cl_set_lower_screen_0d_04_18_effects_regs:
  ld      a, 0x14
  ld      de, 0x14
  ld      hl, 0x5094
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_0d_07_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_0d_07_18_setup_regs:
  ld      bc, 0x070d
  ret

cl_set_lower_screen_0d_07_18_effects:
  _strh   0x070d, S_POSN_X_L
  _strh   0x070d, ECHO_E_X
  _strh   0x5034, DF_CC_L
  ret

cl_set_lower_screen_0d_07_18_effects_regs:
  ld      a, 0x14
  ld      de, 0x14
  ld      hl, 0x5034
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_0d_0a_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_0d_0a_18_setup_regs:
  ld      bc, 0x0a0d
  ret

cl_set_lower_screen_0d_0a_18_effects:
  _strh   0x0a0d, S_POSN_X_L
  _strh   0x0a0d, ECHO_E_X
  _strh   0x48d4, DF_CC_L
  ret

cl_set_lower_screen_0d_0a_18_effects_regs:
  ld      a, 0x14
  ld      de, 0x14
  ld      hl, 0x48d4
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_0d_0d_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_0d_0d_18_setup_regs:
  ld      bc, 0x0d0d
  ret

cl_set_lower_screen_0d_0d_18_effects:
  _strh   0x0d0d, S_POSN_X_L
  _strh   0x0d0d, ECHO_E_X
  _strh   0x4874, DF_CC_L
  ret

cl_set_lower_screen_0d_0d_18_effects_regs:
  ld      a, 0x14
  ld      de, 0x14
  ld      hl, 0x4874
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_0d_10_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_0d_10_18_setup_regs:
  ld      bc, 0x100d
  ret

cl_set_lower_screen_0d_10_18_effects:
  _strh   0x100d, S_POSN_X_L
  _strh   0x100d, ECHO_E_X
  _strh   0x4814, DF_CC_L
  ret

cl_set_lower_screen_0d_10_18_effects_regs:
  ld      a, 0x14
  ld      de, 0x14
  ld      hl, 0x4814
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_0d_13_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_0d_13_18_setup_regs:
  ld      bc, 0x130d
  ret

cl_set_lower_screen_0d_13_18_effects:
  _strh   0x130d, S_POSN_X_L
  _strh   0x130d, ECHO_E_X
  _strh   0x40b4, DF_CC_L
  ret

cl_set_lower_screen_0d_13_18_effects_regs:
  ld      a, 0x14
  ld      de, 0x14
  ld      hl, 0x40b4
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_0d_16_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_0d_16_18_setup_regs:
  ld      bc, 0x160d
  ret

cl_set_lower_screen_0d_16_18_effects:
  _strh   0x160d, S_POSN_X_L
  _strh   0x160d, ECHO_E_X
  _strh   0x4054, DF_CC_L
  ret

cl_set_lower_screen_0d_16_18_effects_regs:
  ld      a, 0x14
  ld      de, 0x14
  ld      hl, 0x4054
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_17_18_01_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x01, DF_SZ
  ret

cl_set_lower_screen_17_18_01_setup_regs:
  ld      bc, 0x1817
  ret

cl_set_lower_screen_17_18_01_effects:
  _strh   0x1817, S_POSN_X_L
  _strh   0x1817, ECHO_E_X
  _strh   0x50ea, DF_CC_L
  ret

cl_set_lower_screen_17_18_01_effects_regs:
  ld      a, 0x0a
  ld      de, 0x0a
  ld      hl, 0x50ea
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_17_0d_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_17_0d_0c_setup_regs:
  ld      bc, 0x0d17
  ret

cl_set_lower_screen_17_0d_0c_effects:
  _strh   0x0d17, S_POSN_X_L
  _strh   0x0d17, ECHO_E_X
  _strh   0x50ea, DF_CC_L
  ret

cl_set_lower_screen_17_0d_0c_effects_regs:
  ld      a, 0x0a
  ld      de, 0x0a
  ld      hl, 0x50ea
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_17_10_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_17_10_0c_setup_regs:
  ld      bc, 0x1017
  ret

cl_set_lower_screen_17_10_0c_effects:
  _strh   0x1017, S_POSN_X_L
  _strh   0x1017, ECHO_E_X
  _strh   0x508a, DF_CC_L
  ret

cl_set_lower_screen_17_10_0c_effects_regs:
  ld      a, 0x0a
  ld      de, 0x0a
  ld      hl, 0x508a
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_17_13_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_17_13_0c_setup_regs:
  ld      bc, 0x1317
  ret

cl_set_lower_screen_17_13_0c_effects:
  _strh   0x1317, S_POSN_X_L
  _strh   0x1317, ECHO_E_X
  _strh   0x502a, DF_CC_L
  ret

cl_set_lower_screen_17_13_0c_effects_regs:
  ld      a, 0x0a
  ld      de, 0x0a
  ld      hl, 0x502a
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_17_16_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_17_16_0c_setup_regs:
  ld      bc, 0x1617
  ret

cl_set_lower_screen_17_16_0c_effects:
  _strh   0x1617, S_POSN_X_L
  _strh   0x1617, ECHO_E_X
  _strh   0x48ca, DF_CC_L
  ret

cl_set_lower_screen_17_16_0c_effects_regs:
  ld      a, 0x0a
  ld      de, 0x0a
  ld      hl, 0x48ca
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_17_06_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_17_06_13_setup_regs:
  ld      bc, 0x0617
  ret

cl_set_lower_screen_17_06_13_effects:
  _strh   0x0617, S_POSN_X_L
  _strh   0x0617, ECHO_E_X
  _strh   0x50ea, DF_CC_L
  ret

cl_set_lower_screen_17_06_13_effects_regs:
  ld      a, 0x0a
  ld      de, 0x0a
  ld      hl, 0x50ea
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_17_09_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_17_09_13_setup_regs:
  ld      bc, 0x0917
  ret

cl_set_lower_screen_17_09_13_effects:
  _strh   0x0917, S_POSN_X_L
  _strh   0x0917, ECHO_E_X
  _strh   0x508a, DF_CC_L
  ret

cl_set_lower_screen_17_09_13_effects_regs:
  ld      a, 0x0a
  ld      de, 0x0a
  ld      hl, 0x508a
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_17_0c_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_17_0c_13_setup_regs:
  ld      bc, 0x0c17
  ret

cl_set_lower_screen_17_0c_13_effects:
  _strh   0x0c17, S_POSN_X_L
  _strh   0x0c17, ECHO_E_X
  _strh   0x502a, DF_CC_L
  ret

cl_set_lower_screen_17_0c_13_effects_regs:
  ld      a, 0x0a
  ld      de, 0x0a
  ld      hl, 0x502a
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_17_0f_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_17_0f_13_setup_regs:
  ld      bc, 0x0f17
  ret

cl_set_lower_screen_17_0f_13_effects:
  _strh   0x0f17, S_POSN_X_L
  _strh   0x0f17, ECHO_E_X
  _strh   0x48ca, DF_CC_L
  ret

cl_set_lower_screen_17_0f_13_effects_regs:
  ld      a, 0x0a
  ld      de, 0x0a
  ld      hl, 0x48ca
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_17_12_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_17_12_13_setup_regs:
  ld      bc, 0x1217
  ret

cl_set_lower_screen_17_12_13_effects:
  _strh   0x1217, S_POSN_X_L
  _strh   0x1217, ECHO_E_X
  _strh   0x486a, DF_CC_L
  ret

cl_set_lower_screen_17_12_13_effects_regs:
  ld      a, 0x0a
  ld      de, 0x0a
  ld      hl, 0x486a
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_17_15_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_17_15_13_setup_regs:
  ld      bc, 0x1517
  ret

cl_set_lower_screen_17_15_13_effects:
  _strh   0x1517, S_POSN_X_L
  _strh   0x1517, ECHO_E_X
  _strh   0x480a, DF_CC_L
  ret

cl_set_lower_screen_17_15_13_effects_regs:
  ld      a, 0x0a
  ld      de, 0x0a
  ld      hl, 0x480a
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_17_18_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_17_18_13_setup_regs:
  ld      bc, 0x1817
  ret

cl_set_lower_screen_17_18_13_effects:
  _strh   0x1817, S_POSN_X_L
  _strh   0x1817, ECHO_E_X
  _strh   0x40aa, DF_CC_L
  ret

cl_set_lower_screen_17_18_13_effects_regs:
  ld      a, 0x0a
  ld      de, 0x0a
  ld      hl, 0x40aa
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_17_01_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_17_01_18_setup_regs:
  ld      bc, 0x0117
  ret

cl_set_lower_screen_17_01_18_effects:
  _strh   0x0117, S_POSN_X_L
  _strh   0x0117, ECHO_E_X
  _strh   0x50ea, DF_CC_L
  ret

cl_set_lower_screen_17_01_18_effects_regs:
  ld      a, 0x0a
  ld      de, 0x0a
  ld      hl, 0x50ea
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_17_04_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_17_04_18_setup_regs:
  ld      bc, 0x0417
  ret

cl_set_lower_screen_17_04_18_effects:
  _strh   0x0417, S_POSN_X_L
  _strh   0x0417, ECHO_E_X
  _strh   0x508a, DF_CC_L
  ret

cl_set_lower_screen_17_04_18_effects_regs:
  ld      a, 0x0a
  ld      de, 0x0a
  ld      hl, 0x508a
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_17_07_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_17_07_18_setup_regs:
  ld      bc, 0x0717
  ret

cl_set_lower_screen_17_07_18_effects:
  _strh   0x0717, S_POSN_X_L
  _strh   0x0717, ECHO_E_X
  _strh   0x502a, DF_CC_L
  ret

cl_set_lower_screen_17_07_18_effects_regs:
  ld      a, 0x0a
  ld      de, 0x0a
  ld      hl, 0x502a
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_17_0a_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_17_0a_18_setup_regs:
  ld      bc, 0x0a17
  ret

cl_set_lower_screen_17_0a_18_effects:
  _strh   0x0a17, S_POSN_X_L
  _strh   0x0a17, ECHO_E_X
  _strh   0x48ca, DF_CC_L
  ret

cl_set_lower_screen_17_0a_18_effects_regs:
  ld      a, 0x0a
  ld      de, 0x0a
  ld      hl, 0x48ca
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_17_0d_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_17_0d_18_setup_regs:
  ld      bc, 0x0d17
  ret

cl_set_lower_screen_17_0d_18_effects:
  _strh   0x0d17, S_POSN_X_L
  _strh   0x0d17, ECHO_E_X
  _strh   0x486a, DF_CC_L
  ret

cl_set_lower_screen_17_0d_18_effects_regs:
  ld      a, 0x0a
  ld      de, 0x0a
  ld      hl, 0x486a
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_17_10_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_17_10_18_setup_regs:
  ld      bc, 0x1017
  ret

cl_set_lower_screen_17_10_18_effects:
  _strh   0x1017, S_POSN_X_L
  _strh   0x1017, ECHO_E_X
  _strh   0x480a, DF_CC_L
  ret

cl_set_lower_screen_17_10_18_effects_regs:
  ld      a, 0x0a
  ld      de, 0x0a
  ld      hl, 0x480a
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_17_13_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_17_13_18_setup_regs:
  ld      bc, 0x1317
  ret

cl_set_lower_screen_17_13_18_effects:
  _strh   0x1317, S_POSN_X_L
  _strh   0x1317, ECHO_E_X
  _strh   0x40aa, DF_CC_L
  ret

cl_set_lower_screen_17_13_18_effects_regs:
  ld      a, 0x0a
  ld      de, 0x0a
  ld      hl, 0x40aa
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_17_16_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_17_16_18_setup_regs:
  ld      bc, 0x1617
  ret

cl_set_lower_screen_17_16_18_effects:
  _strh   0x1617, S_POSN_X_L
  _strh   0x1617, ECHO_E_X
  _strh   0x404a, DF_CC_L
  ret

cl_set_lower_screen_17_16_18_effects_regs:
  ld      a, 0x0a
  ld      de, 0x0a
  ld      hl, 0x404a
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_1f_18_01_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x01, DF_SZ
  ret

cl_set_lower_screen_1f_18_01_setup_regs:
  ld      bc, 0x181f
  ret

cl_set_lower_screen_1f_18_01_effects:
  _strh   0x181f, S_POSN_X_L
  _strh   0x181f, ECHO_E_X
  _strh   0x50e2, DF_CC_L
  ret

cl_set_lower_screen_1f_18_01_effects_regs:
  ld      a, 0x02
  ld      de, 0x02
  ld      hl, 0x50e2
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_1f_0d_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_1f_0d_0c_setup_regs:
  ld      bc, 0x0d1f
  ret

cl_set_lower_screen_1f_0d_0c_effects:
  _strh   0x0d1f, S_POSN_X_L
  _strh   0x0d1f, ECHO_E_X
  _strh   0x50e2, DF_CC_L
  ret

cl_set_lower_screen_1f_0d_0c_effects_regs:
  ld      a, 0x02
  ld      de, 0x02
  ld      hl, 0x50e2
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_1f_10_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_1f_10_0c_setup_regs:
  ld      bc, 0x101f
  ret

cl_set_lower_screen_1f_10_0c_effects:
  _strh   0x101f, S_POSN_X_L
  _strh   0x101f, ECHO_E_X
  _strh   0x5082, DF_CC_L
  ret

cl_set_lower_screen_1f_10_0c_effects_regs:
  ld      a, 0x02
  ld      de, 0x02
  ld      hl, 0x5082
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_1f_13_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_1f_13_0c_setup_regs:
  ld      bc, 0x131f
  ret

cl_set_lower_screen_1f_13_0c_effects:
  _strh   0x131f, S_POSN_X_L
  _strh   0x131f, ECHO_E_X
  _strh   0x5022, DF_CC_L
  ret

cl_set_lower_screen_1f_13_0c_effects_regs:
  ld      a, 0x02
  ld      de, 0x02
  ld      hl, 0x5022
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_1f_16_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_1f_16_0c_setup_regs:
  ld      bc, 0x161f
  ret

cl_set_lower_screen_1f_16_0c_effects:
  _strh   0x161f, S_POSN_X_L
  _strh   0x161f, ECHO_E_X
  _strh   0x48c2, DF_CC_L
  ret

cl_set_lower_screen_1f_16_0c_effects_regs:
  ld      a, 0x02
  ld      de, 0x02
  ld      hl, 0x48c2
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_1f_06_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_1f_06_13_setup_regs:
  ld      bc, 0x061f
  ret

cl_set_lower_screen_1f_06_13_effects:
  _strh   0x061f, S_POSN_X_L
  _strh   0x061f, ECHO_E_X
  _strh   0x50e2, DF_CC_L
  ret

cl_set_lower_screen_1f_06_13_effects_regs:
  ld      a, 0x02
  ld      de, 0x02
  ld      hl, 0x50e2
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_1f_09_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_1f_09_13_setup_regs:
  ld      bc, 0x091f
  ret

cl_set_lower_screen_1f_09_13_effects:
  _strh   0x091f, S_POSN_X_L
  _strh   0x091f, ECHO_E_X
  _strh   0x5082, DF_CC_L
  ret

cl_set_lower_screen_1f_09_13_effects_regs:
  ld      a, 0x02
  ld      de, 0x02
  ld      hl, 0x5082
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_1f_0c_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_1f_0c_13_setup_regs:
  ld      bc, 0x0c1f
  ret

cl_set_lower_screen_1f_0c_13_effects:
  _strh   0x0c1f, S_POSN_X_L
  _strh   0x0c1f, ECHO_E_X
  _strh   0x5022, DF_CC_L
  ret

cl_set_lower_screen_1f_0c_13_effects_regs:
  ld      a, 0x02
  ld      de, 0x02
  ld      hl, 0x5022
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_1f_0f_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_1f_0f_13_setup_regs:
  ld      bc, 0x0f1f
  ret

cl_set_lower_screen_1f_0f_13_effects:
  _strh   0x0f1f, S_POSN_X_L
  _strh   0x0f1f, ECHO_E_X
  _strh   0x48c2, DF_CC_L
  ret

cl_set_lower_screen_1f_0f_13_effects_regs:
  ld      a, 0x02
  ld      de, 0x02
  ld      hl, 0x48c2
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_1f_12_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_1f_12_13_setup_regs:
  ld      bc, 0x121f
  ret

cl_set_lower_screen_1f_12_13_effects:
  _strh   0x121f, S_POSN_X_L
  _strh   0x121f, ECHO_E_X
  _strh   0x4862, DF_CC_L
  ret

cl_set_lower_screen_1f_12_13_effects_regs:
  ld      a, 0x02
  ld      de, 0x02
  ld      hl, 0x4862
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_1f_15_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_1f_15_13_setup_regs:
  ld      bc, 0x151f
  ret

cl_set_lower_screen_1f_15_13_effects:
  _strh   0x151f, S_POSN_X_L
  _strh   0x151f, ECHO_E_X
  _strh   0x4802, DF_CC_L
  ret

cl_set_lower_screen_1f_15_13_effects_regs:
  ld      a, 0x02
  ld      de, 0x02
  ld      hl, 0x4802
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_1f_18_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_1f_18_13_setup_regs:
  ld      bc, 0x181f
  ret

cl_set_lower_screen_1f_18_13_effects:
  _strh   0x181f, S_POSN_X_L
  _strh   0x181f, ECHO_E_X
  _strh   0x40a2, DF_CC_L
  ret

cl_set_lower_screen_1f_18_13_effects_regs:
  ld      a, 0x02
  ld      de, 0x02
  ld      hl, 0x40a2
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_1f_01_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_1f_01_18_setup_regs:
  ld      bc, 0x011f
  ret

cl_set_lower_screen_1f_01_18_effects:
  _strh   0x011f, S_POSN_X_L
  _strh   0x011f, ECHO_E_X
  _strh   0x50e2, DF_CC_L
  ret

cl_set_lower_screen_1f_01_18_effects_regs:
  ld      a, 0x02
  ld      de, 0x02
  ld      hl, 0x50e2
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_1f_04_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_1f_04_18_setup_regs:
  ld      bc, 0x041f
  ret

cl_set_lower_screen_1f_04_18_effects:
  _strh   0x041f, S_POSN_X_L
  _strh   0x041f, ECHO_E_X
  _strh   0x5082, DF_CC_L
  ret

cl_set_lower_screen_1f_04_18_effects_regs:
  ld      a, 0x02
  ld      de, 0x02
  ld      hl, 0x5082
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_1f_07_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_1f_07_18_setup_regs:
  ld      bc, 0x071f
  ret

cl_set_lower_screen_1f_07_18_effects:
  _strh   0x071f, S_POSN_X_L
  _strh   0x071f, ECHO_E_X
  _strh   0x5022, DF_CC_L
  ret

cl_set_lower_screen_1f_07_18_effects_regs:
  ld      a, 0x02
  ld      de, 0x02
  ld      hl, 0x5022
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_1f_0a_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_1f_0a_18_setup_regs:
  ld      bc, 0x0a1f
  ret

cl_set_lower_screen_1f_0a_18_effects:
  _strh   0x0a1f, S_POSN_X_L
  _strh   0x0a1f, ECHO_E_X
  _strh   0x48c2, DF_CC_L
  ret

cl_set_lower_screen_1f_0a_18_effects_regs:
  ld      a, 0x02
  ld      de, 0x02
  ld      hl, 0x48c2
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_1f_0d_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_1f_0d_18_setup_regs:
  ld      bc, 0x0d1f
  ret

cl_set_lower_screen_1f_0d_18_effects:
  _strh   0x0d1f, S_POSN_X_L
  _strh   0x0d1f, ECHO_E_X
  _strh   0x4862, DF_CC_L
  ret

cl_set_lower_screen_1f_0d_18_effects_regs:
  ld      a, 0x02
  ld      de, 0x02
  ld      hl, 0x4862
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_1f_10_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_1f_10_18_setup_regs:
  ld      bc, 0x101f
  ret

cl_set_lower_screen_1f_10_18_effects:
  _strh   0x101f, S_POSN_X_L
  _strh   0x101f, ECHO_E_X
  _strh   0x4802, DF_CC_L
  ret

cl_set_lower_screen_1f_10_18_effects_regs:
  ld      a, 0x02
  ld      de, 0x02
  ld      hl, 0x4802
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_1f_13_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_1f_13_18_setup_regs:
  ld      bc, 0x131f
  ret

cl_set_lower_screen_1f_13_18_effects:
  _strh   0x131f, S_POSN_X_L
  _strh   0x131f, ECHO_E_X
  _strh   0x40a2, DF_CC_L
  ret

cl_set_lower_screen_1f_13_18_effects_regs:
  ld      a, 0x02
  ld      de, 0x02
  ld      hl, 0x40a2
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_1f_16_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_1f_16_18_setup_regs:
  ld      bc, 0x161f
  ret

cl_set_lower_screen_1f_16_18_effects:
  _strh   0x161f, S_POSN_X_L
  _strh   0x161f, ECHO_E_X
  _strh   0x4042, DF_CC_L
  ret

cl_set_lower_screen_1f_16_18_effects_regs:
  ld      a, 0x02
  ld      de, 0x02
  ld      hl, 0x4042
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_20_18_01_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x01, DF_SZ
  ret

cl_set_lower_screen_20_18_01_setup_regs:
  ld      bc, 0x1820
  ret

cl_set_lower_screen_20_18_01_effects:
  _strh   0x1820, S_POSN_X_L
  _strh   0x1820, ECHO_E_X
  _strh   0x50e1, DF_CC_L
  ret

cl_set_lower_screen_20_18_01_effects_regs:
  ld      a, 0x01
  ld      de, 0x01
  ld      hl, 0x50e1
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_20_0d_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_20_0d_0c_setup_regs:
  ld      bc, 0x0d20
  ret

cl_set_lower_screen_20_0d_0c_effects:
  _strh   0x0d20, S_POSN_X_L
  _strh   0x0d20, ECHO_E_X
  _strh   0x50e1, DF_CC_L
  ret

cl_set_lower_screen_20_0d_0c_effects_regs:
  ld      a, 0x01
  ld      de, 0x01
  ld      hl, 0x50e1
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_20_10_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_20_10_0c_setup_regs:
  ld      bc, 0x1020
  ret

cl_set_lower_screen_20_10_0c_effects:
  _strh   0x1020, S_POSN_X_L
  _strh   0x1020, ECHO_E_X
  _strh   0x5081, DF_CC_L
  ret

cl_set_lower_screen_20_10_0c_effects_regs:
  ld      a, 0x01
  ld      de, 0x01
  ld      hl, 0x5081
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_20_13_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_20_13_0c_setup_regs:
  ld      bc, 0x1320
  ret

cl_set_lower_screen_20_13_0c_effects:
  _strh   0x1320, S_POSN_X_L
  _strh   0x1320, ECHO_E_X
  _strh   0x5021, DF_CC_L
  ret

cl_set_lower_screen_20_13_0c_effects_regs:
  ld      a, 0x01
  ld      de, 0x01
  ld      hl, 0x5021
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_20_16_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_20_16_0c_setup_regs:
  ld      bc, 0x1620
  ret

cl_set_lower_screen_20_16_0c_effects:
  _strh   0x1620, S_POSN_X_L
  _strh   0x1620, ECHO_E_X
  _strh   0x48c1, DF_CC_L
  ret

cl_set_lower_screen_20_16_0c_effects_regs:
  ld      a, 0x01
  ld      de, 0x01
  ld      hl, 0x48c1
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_20_06_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_20_06_13_setup_regs:
  ld      bc, 0x0620
  ret

cl_set_lower_screen_20_06_13_effects:
  _strh   0x0620, S_POSN_X_L
  _strh   0x0620, ECHO_E_X
  _strh   0x50e1, DF_CC_L
  ret

cl_set_lower_screen_20_06_13_effects_regs:
  ld      a, 0x01
  ld      de, 0x01
  ld      hl, 0x50e1
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_20_09_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_20_09_13_setup_regs:
  ld      bc, 0x0920
  ret

cl_set_lower_screen_20_09_13_effects:
  _strh   0x0920, S_POSN_X_L
  _strh   0x0920, ECHO_E_X
  _strh   0x5081, DF_CC_L
  ret

cl_set_lower_screen_20_09_13_effects_regs:
  ld      a, 0x01
  ld      de, 0x01
  ld      hl, 0x5081
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_20_0c_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_20_0c_13_setup_regs:
  ld      bc, 0x0c20
  ret

cl_set_lower_screen_20_0c_13_effects:
  _strh   0x0c20, S_POSN_X_L
  _strh   0x0c20, ECHO_E_X
  _strh   0x5021, DF_CC_L
  ret

cl_set_lower_screen_20_0c_13_effects_regs:
  ld      a, 0x01
  ld      de, 0x01
  ld      hl, 0x5021
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_20_0f_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_20_0f_13_setup_regs:
  ld      bc, 0x0f20
  ret

cl_set_lower_screen_20_0f_13_effects:
  _strh   0x0f20, S_POSN_X_L
  _strh   0x0f20, ECHO_E_X
  _strh   0x48c1, DF_CC_L
  ret

cl_set_lower_screen_20_0f_13_effects_regs:
  ld      a, 0x01
  ld      de, 0x01
  ld      hl, 0x48c1
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_20_12_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_20_12_13_setup_regs:
  ld      bc, 0x1220
  ret

cl_set_lower_screen_20_12_13_effects:
  _strh   0x1220, S_POSN_X_L
  _strh   0x1220, ECHO_E_X
  _strh   0x4861, DF_CC_L
  ret

cl_set_lower_screen_20_12_13_effects_regs:
  ld      a, 0x01
  ld      de, 0x01
  ld      hl, 0x4861
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_20_15_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_20_15_13_setup_regs:
  ld      bc, 0x1520
  ret

cl_set_lower_screen_20_15_13_effects:
  _strh   0x1520, S_POSN_X_L
  _strh   0x1520, ECHO_E_X
  _strh   0x4801, DF_CC_L
  ret

cl_set_lower_screen_20_15_13_effects_regs:
  ld      a, 0x01
  ld      de, 0x01
  ld      hl, 0x4801
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_20_18_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_20_18_13_setup_regs:
  ld      bc, 0x1820
  ret

cl_set_lower_screen_20_18_13_effects:
  _strh   0x1820, S_POSN_X_L
  _strh   0x1820, ECHO_E_X
  _strh   0x40a1, DF_CC_L
  ret

cl_set_lower_screen_20_18_13_effects_regs:
  ld      a, 0x01
  ld      de, 0x01
  ld      hl, 0x40a1
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_20_01_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_20_01_18_setup_regs:
  ld      bc, 0x0120
  ret

cl_set_lower_screen_20_01_18_effects:
  _strh   0x0120, S_POSN_X_L
  _strh   0x0120, ECHO_E_X
  _strh   0x50e1, DF_CC_L
  ret

cl_set_lower_screen_20_01_18_effects_regs:
  ld      a, 0x01
  ld      de, 0x01
  ld      hl, 0x50e1
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_20_04_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_20_04_18_setup_regs:
  ld      bc, 0x0420
  ret

cl_set_lower_screen_20_04_18_effects:
  _strh   0x0420, S_POSN_X_L
  _strh   0x0420, ECHO_E_X
  _strh   0x5081, DF_CC_L
  ret

cl_set_lower_screen_20_04_18_effects_regs:
  ld      a, 0x01
  ld      de, 0x01
  ld      hl, 0x5081
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_20_07_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_20_07_18_setup_regs:
  ld      bc, 0x0720
  ret

cl_set_lower_screen_20_07_18_effects:
  _strh   0x0720, S_POSN_X_L
  _strh   0x0720, ECHO_E_X
  _strh   0x5021, DF_CC_L
  ret

cl_set_lower_screen_20_07_18_effects_regs:
  ld      a, 0x01
  ld      de, 0x01
  ld      hl, 0x5021
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_20_0a_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_20_0a_18_setup_regs:
  ld      bc, 0x0a20
  ret

cl_set_lower_screen_20_0a_18_effects:
  _strh   0x0a20, S_POSN_X_L
  _strh   0x0a20, ECHO_E_X
  _strh   0x48c1, DF_CC_L
  ret

cl_set_lower_screen_20_0a_18_effects_regs:
  ld      a, 0x01
  ld      de, 0x01
  ld      hl, 0x48c1
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_20_0d_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_20_0d_18_setup_regs:
  ld      bc, 0x0d20
  ret

cl_set_lower_screen_20_0d_18_effects:
  _strh   0x0d20, S_POSN_X_L
  _strh   0x0d20, ECHO_E_X
  _strh   0x4861, DF_CC_L
  ret

cl_set_lower_screen_20_0d_18_effects_regs:
  ld      a, 0x01
  ld      de, 0x01
  ld      hl, 0x4861
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_20_10_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_20_10_18_setup_regs:
  ld      bc, 0x1020
  ret

cl_set_lower_screen_20_10_18_effects:
  _strh   0x1020, S_POSN_X_L
  _strh   0x1020, ECHO_E_X
  _strh   0x4801, DF_CC_L
  ret

cl_set_lower_screen_20_10_18_effects_regs:
  ld      a, 0x01
  ld      de, 0x01
  ld      hl, 0x4801
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_20_13_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_20_13_18_setup_regs:
  ld      bc, 0x1320
  ret

cl_set_lower_screen_20_13_18_effects:
  _strh   0x1320, S_POSN_X_L
  _strh   0x1320, ECHO_E_X
  _strh   0x40a1, DF_CC_L
  ret

cl_set_lower_screen_20_13_18_effects_regs:
  ld      a, 0x01
  ld      de, 0x01
  ld      hl, 0x40a1
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_20_16_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_20_16_18_setup_regs:
  ld      bc, 0x1620
  ret

cl_set_lower_screen_20_16_18_effects:
  _strh   0x1620, S_POSN_X_L
  _strh   0x1620, ECHO_E_X
  _strh   0x4041, DF_CC_L
  ret

cl_set_lower_screen_20_16_18_effects_regs:
  ld      a, 0x01
  ld      de, 0x01
  ld      hl, 0x4041
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_21_18_01_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x01, DF_SZ
  ret

cl_set_lower_screen_21_18_01_setup_regs:
  ld      bc, 0x1821
  ret

cl_set_lower_screen_21_18_01_effects:
  _strh   0x1821, S_POSN_X_L
  _strh   0x1821, ECHO_E_X
  _strh   0x50e0, DF_CC_L
  ret

cl_set_lower_screen_21_18_01_effects_regs:
  ld      a, 0x00
  ld      de, 0x00
  ld      hl, 0x50e0
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_21_0d_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_21_0d_0c_setup_regs:
  ld      bc, 0x0d21
  ret

cl_set_lower_screen_21_0d_0c_effects:
  _strh   0x0d21, S_POSN_X_L
  _strh   0x0d21, ECHO_E_X
  _strh   0x50e0, DF_CC_L
  ret

cl_set_lower_screen_21_0d_0c_effects_regs:
  ld      a, 0x00
  ld      de, 0x00
  ld      hl, 0x50e0
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_21_10_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_21_10_0c_setup_regs:
  ld      bc, 0x1021
  ret

cl_set_lower_screen_21_10_0c_effects:
  _strh   0x1021, S_POSN_X_L
  _strh   0x1021, ECHO_E_X
  _strh   0x5080, DF_CC_L
  ret

cl_set_lower_screen_21_10_0c_effects_regs:
  ld      a, 0x00
  ld      de, 0x00
  ld      hl, 0x5080
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_21_13_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_21_13_0c_setup_regs:
  ld      bc, 0x1321
  ret

cl_set_lower_screen_21_13_0c_effects:
  _strh   0x1321, S_POSN_X_L
  _strh   0x1321, ECHO_E_X
  _strh   0x5020, DF_CC_L
  ret

cl_set_lower_screen_21_13_0c_effects_regs:
  ld      a, 0x00
  ld      de, 0x00
  ld      hl, 0x5020
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_21_16_0c_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x0c, DF_SZ
  ret

cl_set_lower_screen_21_16_0c_setup_regs:
  ld      bc, 0x1621
  ret

cl_set_lower_screen_21_16_0c_effects:
  _strh   0x1621, S_POSN_X_L
  _strh   0x1621, ECHO_E_X
  _strh   0x48c0, DF_CC_L
  ret

cl_set_lower_screen_21_16_0c_effects_regs:
  ld      a, 0x00
  ld      de, 0x00
  ld      hl, 0x48c0
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_21_06_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_21_06_13_setup_regs:
  ld      bc, 0x0621
  ret

cl_set_lower_screen_21_06_13_effects:
  _strh   0x0621, S_POSN_X_L
  _strh   0x0621, ECHO_E_X
  _strh   0x50e0, DF_CC_L
  ret

cl_set_lower_screen_21_06_13_effects_regs:
  ld      a, 0x00
  ld      de, 0x00
  ld      hl, 0x50e0
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_21_09_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_21_09_13_setup_regs:
  ld      bc, 0x0921
  ret

cl_set_lower_screen_21_09_13_effects:
  _strh   0x0921, S_POSN_X_L
  _strh   0x0921, ECHO_E_X
  _strh   0x5080, DF_CC_L
  ret

cl_set_lower_screen_21_09_13_effects_regs:
  ld      a, 0x00
  ld      de, 0x00
  ld      hl, 0x5080
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_21_0c_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_21_0c_13_setup_regs:
  ld      bc, 0x0c21
  ret

cl_set_lower_screen_21_0c_13_effects:
  _strh   0x0c21, S_POSN_X_L
  _strh   0x0c21, ECHO_E_X
  _strh   0x5020, DF_CC_L
  ret

cl_set_lower_screen_21_0c_13_effects_regs:
  ld      a, 0x00
  ld      de, 0x00
  ld      hl, 0x5020
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_21_0f_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_21_0f_13_setup_regs:
  ld      bc, 0x0f21
  ret

cl_set_lower_screen_21_0f_13_effects:
  _strh   0x0f21, S_POSN_X_L
  _strh   0x0f21, ECHO_E_X
  _strh   0x48c0, DF_CC_L
  ret

cl_set_lower_screen_21_0f_13_effects_regs:
  ld      a, 0x00
  ld      de, 0x00
  ld      hl, 0x48c0
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_21_12_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_21_12_13_setup_regs:
  ld      bc, 0x1221
  ret

cl_set_lower_screen_21_12_13_effects:
  _strh   0x1221, S_POSN_X_L
  _strh   0x1221, ECHO_E_X
  _strh   0x4860, DF_CC_L
  ret

cl_set_lower_screen_21_12_13_effects_regs:
  ld      a, 0x00
  ld      de, 0x00
  ld      hl, 0x4860
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_21_15_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_21_15_13_setup_regs:
  ld      bc, 0x1521
  ret

cl_set_lower_screen_21_15_13_effects:
  _strh   0x1521, S_POSN_X_L
  _strh   0x1521, ECHO_E_X
  _strh   0x4800, DF_CC_L
  ret

cl_set_lower_screen_21_15_13_effects_regs:
  ld      a, 0x00
  ld      de, 0x00
  ld      hl, 0x4800
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_21_18_13_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x13, DF_SZ
  ret

cl_set_lower_screen_21_18_13_setup_regs:
  ld      bc, 0x1821
  ret

cl_set_lower_screen_21_18_13_effects:
  _strh   0x1821, S_POSN_X_L
  _strh   0x1821, ECHO_E_X
  _strh   0x40a0, DF_CC_L
  ret

cl_set_lower_screen_21_18_13_effects_regs:
  ld      a, 0x00
  ld      de, 0x00
  ld      hl, 0x40a0
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_21_01_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_21_01_18_setup_regs:
  ld      bc, 0x0121
  ret

cl_set_lower_screen_21_01_18_effects:
  _strh   0x0121, S_POSN_X_L
  _strh   0x0121, ECHO_E_X
  _strh   0x50e0, DF_CC_L
  ret

cl_set_lower_screen_21_01_18_effects_regs:
  ld      a, 0x00
  ld      de, 0x00
  ld      hl, 0x50e0
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_21_04_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_21_04_18_setup_regs:
  ld      bc, 0x0421
  ret

cl_set_lower_screen_21_04_18_effects:
  _strh   0x0421, S_POSN_X_L
  _strh   0x0421, ECHO_E_X
  _strh   0x5080, DF_CC_L
  ret

cl_set_lower_screen_21_04_18_effects_regs:
  ld      a, 0x00
  ld      de, 0x00
  ld      hl, 0x5080
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_21_07_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_21_07_18_setup_regs:
  ld      bc, 0x0721
  ret

cl_set_lower_screen_21_07_18_effects:
  _strh   0x0721, S_POSN_X_L
  _strh   0x0721, ECHO_E_X
  _strh   0x5020, DF_CC_L
  ret

cl_set_lower_screen_21_07_18_effects_regs:
  ld      a, 0x00
  ld      de, 0x00
  ld      hl, 0x5020
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_21_0a_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_21_0a_18_setup_regs:
  ld      bc, 0x0a21
  ret

cl_set_lower_screen_21_0a_18_effects:
  _strh   0x0a21, S_POSN_X_L
  _strh   0x0a21, ECHO_E_X
  _strh   0x48c0, DF_CC_L
  ret

cl_set_lower_screen_21_0a_18_effects_regs:
  ld      a, 0x00
  ld      de, 0x00
  ld      hl, 0x48c0
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_21_0d_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_21_0d_18_setup_regs:
  ld      bc, 0x0d21
  ret

cl_set_lower_screen_21_0d_18_effects:
  _strh   0x0d21, S_POSN_X_L
  _strh   0x0d21, ECHO_E_X
  _strh   0x4860, DF_CC_L
  ret

cl_set_lower_screen_21_0d_18_effects_regs:
  ld      a, 0x00
  ld      de, 0x00
  ld      hl, 0x4860
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_21_10_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_21_10_18_setup_regs:
  ld      bc, 0x1021
  ret

cl_set_lower_screen_21_10_18_effects:
  _strh   0x1021, S_POSN_X_L
  _strh   0x1021, ECHO_E_X
  _strh   0x4800, DF_CC_L
  ret

cl_set_lower_screen_21_10_18_effects_regs:
  ld      a, 0x00
  ld      de, 0x00
  ld      hl, 0x4800
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_21_13_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_21_13_18_setup_regs:
  ld      bc, 0x1321
  ret

cl_set_lower_screen_21_13_18_effects:
  _strh   0x1321, S_POSN_X_L
  _strh   0x1321, ECHO_E_X
  _strh   0x40a0, DF_CC_L
  ret

cl_set_lower_screen_21_13_18_effects_regs:
  ld      a, 0x00
  ld      de, 0x00
  ld      hl, 0x40a0
  ldf     H_FLAG|X3_FLAG
  ret


cl_set_lower_screen_21_16_18_setup:
  _resbit 1, FLAGS
  _setbit 0, TV_FLAG
  _strb   0x18, DF_SZ
  ret

cl_set_lower_screen_21_16_18_setup_regs:
  ld      bc, 0x1621
  ret

cl_set_lower_screen_21_16_18_effects:
  _strh   0x1621, S_POSN_X_L
  _strh   0x1621, ECHO_E_X
  _strh   0x4040, DF_CC_L
  ret

cl_set_lower_screen_21_16_18_effects_regs:
  ld      a, 0x00
  ld      de, 0x00
  ld      hl, 0x4040
  ldf     H_FLAG|X3_FLAG
  ret
