# This file is part of the Spectrum +4 Project.
# Licencing information can be found in the LICENCE file
# (C) 2019 Spectrum +4 Authors. All rights reserved.

# Generated from the files in the /test directory.

# This file is auto-generated by all.sh. DO NOT EDIT!

.text


all_tests:
  .byte 0x01                              ; Number of tests.
  .hword test_CL_ADDR_test_case_1


##########################################################################
############# Test CL-ADDR test case 1 ###################################
##########################################################################

# Test case definition
test_CL_ADDR_test_case_1:
  .hword test_CL_ADDR_test_case_1_name
  .hword test_CL_ADDR_test_case_1_setup_registers
  .hword test_CL_ADDR_test_case_1_effects_registers
  .hword test_CL_ADDR_test_case_1_exec

# Test case name
test_CL_ADDR_test_case_1_name:
  .asciz "CL-ADDR test case 1"

# Test case setup


# Registers setup
test_CL_ADDR_test_case_1_setup_registers:
  .byte 0b00000000
  .byte 0b10000000
                                          ; Bit 7 = 1 => B (register index 15) is absolute value
  .byte 0b00000000
  .byte 11                                ; B = 0x0b

# Test case effects

# Registers effects
test_CL_ADDR_test_case_1_effects_registers:
  .byte 0b00000000
  .byte 0b00110000
                                          ; Bit 4 = 1 => F (register index 12) is absolute value
                                          ; Bit 5 = 1 => A (register index 13) is absolute value
  .byte 0b00001110
                                          ; Bit 1 = 1 => D (register index 17) is absolute value
                                          ; Bit 2 = 1 => L (register index 18) is absolute value
                                          ; Bit 3 = 1 => H (register index 19) is absolute value
  .byte 12                                ; F = 0x0c
  .byte 72                                ; A = 0x48
  .byte 13                                ; D = 0x0d
  .byte 160                               ; L = 0xa0
  .byte 72                                ; H = 0x48

# Test case execution

test_CL_ADDR_test_case_1_exec:
  pop     hl
  call    0x0e9b                          ; CL-ADDR
  jp      test_exec_return

##########################################################################
