# This file is part of the Spectrum +4 Project.
# Licencing information can be found in the LICENCE file
# (C) 2021 Spectrum +4 Authors. All rights reserved.

# This file is auto-generated by test_cl_chan.sh. DO NOT EDIT!

.text


cl_chan_01_setup:
  _strb   0x01, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_01_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x1800, DF_CC_L
  ret

cl_chan_01_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x1800
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_02_setup:
  _strb   0x02, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_02_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x10e0, DF_CC_L
  ret

cl_chan_02_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x10e0
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_03_setup:
  _strb   0x03, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_03_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x10c0, DF_CC_L
  ret

cl_chan_03_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x10c0
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_04_setup:
  _strb   0x04, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_04_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x10a0, DF_CC_L
  ret

cl_chan_04_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x10a0
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_05_setup:
  _strb   0x05, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_05_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x1080, DF_CC_L
  ret

cl_chan_05_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x1080
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_06_setup:
  _strb   0x06, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_06_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x1060, DF_CC_L
  ret

cl_chan_06_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x1060
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_07_setup:
  _strb   0x07, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_07_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x1040, DF_CC_L
  ret

cl_chan_07_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x1040
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_08_setup:
  _strb   0x08, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_08_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x1020, DF_CC_L
  ret

cl_chan_08_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x1020
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_09_setup:
  _strb   0x09, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_09_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x1000, DF_CC_L
  ret

cl_chan_09_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x1000
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_0a_setup:
  _strb   0x0a, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_0a_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x08e0, DF_CC_L
  ret

cl_chan_0a_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x08e0
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_0b_setup:
  _strb   0x0b, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_0b_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x08c0, DF_CC_L
  ret

cl_chan_0b_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x08c0
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_0c_setup:
  _strb   0x0c, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_0c_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x08a0, DF_CC_L
  ret

cl_chan_0c_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x08a0
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_0d_setup:
  _strb   0x0d, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_0d_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x0880, DF_CC_L
  ret

cl_chan_0d_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x0880
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_0e_setup:
  _strb   0x0e, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_0e_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x0860, DF_CC_L
  ret

cl_chan_0e_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x0860
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_0f_setup:
  _strb   0x0f, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_0f_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x0840, DF_CC_L
  ret

cl_chan_0f_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x0840
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_10_setup:
  _strb   0x10, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_10_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x0820, DF_CC_L
  ret

cl_chan_10_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x0820
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_11_setup:
  _strb   0x11, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_11_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x0800, DF_CC_L
  ret

cl_chan_11_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x0800
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_12_setup:
  _strb   0x12, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_12_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x00e0, DF_CC_L
  ret

cl_chan_12_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x00e0
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_13_setup:
  _strb   0x13, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_13_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x00c0, DF_CC_L
  ret

cl_chan_13_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x00c0
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_14_setup:
  _strb   0x14, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_14_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x00a0, DF_CC_L
  ret

cl_chan_14_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x00a0
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_15_setup:
  _strb   0x15, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_15_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x0080, DF_CC_L
  ret

cl_chan_15_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x0080
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_16_setup:
  _strb   0x16, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_16_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x0060, DF_CC_L
  ret

cl_chan_16_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x0060
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_17_setup:
  _strb   0x17, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_17_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x0040, DF_CC_L
  ret

cl_chan_17_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x0040
  ldf     X3_FLAG | H_FLAG
  ret


cl_chan_18_setup:
  _strb   0x18, DF_SZ
  _strb   0x6f, BORDCR
  _strb   0b11110011, P_FLAG
  _strh   0x0001, STRMS                   ; Stream -3 points to first channel
  _strh   0x7000, CHANS
  _strb   'K', 0x7004                     ; Channel identifier for first channel
  ret

cl_chan_18_effects:
  _strh   0x7000, CURCHL                  ; Current channel is keyboard
  _resbit 1, FLAGS                        ; Printer not in use
  _resbit 5, FLAGS                        ; No new key
  _setbit 4, FLAGS2                       ; K channel in use
  _setbit 0, TV_FLAG                      ; Lower screen in use
  _strb   0x6f, ATTR_T                    ; [BORDCR]
  _strb   0x00, MASK_T
  _strb   0b10100010, P_FLAG              ; even (temp) bits cleared
  _strh   print_out, 0x7000
  _strh   key_input, 0x7002
  _strb   33, S_POSN_X_L
  _strb   23, S_POSN_Y_L
  _strb   33, ECHO_E_X
  _strb   23, ECHO_E_Y
  _strh   display_file + 0x0020, DF_CC_L
  ret

cl_chan_18_effects_regs:
  ld      a, 0
  ld      bc, 0x1721
  ld      de, 0
  ld      hl, display_file + 0x0020
  ldf     X3_FLAG | H_FLAG
  ret
