# This file is part of the Spectrum +4 Project.
# Licencing information can be found in the LICENCE file
# (C) 2021 Spectrum +4 Authors. All rights reserved.

# This file is auto-generated by test_po_attr.sh. DO NOT EDIT!

.text


po_attr_00_setup:
  _strb   0x84, ATTR_T
  _strb   0x41, attributes_file + 0x00001319
  _strb   0xf9, MASK_T
  _strb   0xce, P_FLAG
  ret

po_attr_00_setup_regs:
  ldr     x0, = display_file + 0x00029692
  ret

po_attr_00_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00001319
  mov     x1, 0x45
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_00_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00001319
  mov     x1, 0x45
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_01_setup:
  _strb   0x46, ATTR_T
  _strb   0x2b, attributes_file + 0x00000004
  _strb   0x65, MASK_T
  _strb   0xb1, P_FLAG
  ret

po_attr_01_setup_regs:
  ldr     x0, = display_file + 0x00007628
  ret

po_attr_01_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000004
  mov     x1, 0x20
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_01_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000004
  mov     x1, 0x20
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_02_setup:
  _strb   0xcb, ATTR_T
  _strb   0x4d, attributes_file + 0x00000a25
  _strb   0x41, MASK_T
  _strb   0x51, P_FLAG
  ret

po_attr_02_setup_regs:
  ldr     x0, = display_file + 0x0001224a
  ret

po_attr_02_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000a25
  mov     x1, 0xf8
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_02_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000a25
  mov     x1, 0xf8
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_03_setup:
  _strb   0x35, ATTR_T
  _strb   0xff, attributes_file + 0x00000a9e
  _strb   0x26, MASK_T
  _strb   0xd5, P_FLAG
  ret

po_attr_03_setup_regs:
  ldr     x0, = display_file + 0x000144fc
  ret

po_attr_03_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000a9e
  mov     x1, 0x07
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_03_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000a9e
  mov     x1, 0x07
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_04_setup:
  _strb   0xc0, ATTR_T
  _strb   0x63, attributes_file + 0x00001298
  _strb   0xf2, MASK_T
  _strb   0x1e, P_FLAG
  ret

po_attr_04_setup_regs:
  ldr     x0, = display_file + 0x00024130
  ret

po_attr_04_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00001298
  mov     x1, 0x60
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_04_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00001298
  mov     x1, 0x60
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_05_setup:
  _strb   0xd8, ATTR_T
  _strb   0xb5, attributes_file + 0x00000afb
  _strb   0xd9, MASK_T
  _strb   0x74, P_FLAG
  ret

po_attr_05_setup_regs:
  ldr     x0, = display_file + 0x000145b6
  ret

po_attr_05_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000afb
  mov     x1, 0xb8
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_05_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000afb
  mov     x1, 0xb8
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_06_setup:
  _strb   0xf9, ATTR_T
  _strb   0x3a, attributes_file + 0x0000129a
  _strb   0x1f, MASK_T
  _strb   0x5b, P_FLAG
  ret

po_attr_06_setup_regs:
  ldr     x0, = display_file + 0x00021f74
  ret

po_attr_06_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x0000129a
  mov     x1, 0xf8
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_06_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x0000129a
  mov     x1, 0xf8
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_07_setup:
  _strb   0x03, ATTR_T
  _strb   0x56, attributes_file + 0x00000302
  _strb   0x67, MASK_T
  _strb   0x16, P_FLAG
  ret

po_attr_07_setup_regs:
  ldr     x0, = display_file + 0x00007c24
  ret

po_attr_07_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000302
  mov     x1, 0x47
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_07_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000302
  mov     x1, 0x47
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_08_setup:
  _strb   0x1b, ATTR_T
  _strb   0x97, attributes_file + 0x00000961
  _strb   0x58, MASK_T
  _strb   0xe3, P_FLAG
  ret

po_attr_08_setup_regs:
  ldr     x0, = display_file + 0x00010fe2
  ret

po_attr_08_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000961
  mov     x1, 0x3b
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_08_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000961
  mov     x1, 0x3b
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_09_setup:
  _strb   0xbf, ATTR_T
  _strb   0x51, attributes_file + 0x00000144
  _strb   0x21, MASK_T
  _strb   0xac, P_FLAG
  ret

po_attr_09_setup_regs:
  ldr     x0, = display_file + 0x00003528
  ret

po_attr_09_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000144
  mov     x1, 0x9f
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_09_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000144
  mov     x1, 0x9f
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_0a_setup:
  _strb   0x5c, ATTR_T
  _strb   0x60, attributes_file + 0x0000007a
  _strb   0x87, MASK_T
  _strb   0xda, P_FLAG
  ret

po_attr_0a_setup_regs:
  ldr     x0, = display_file + 0x000022b4
  ret

po_attr_0a_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x0000007a
  mov     x1, 0x78
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_0a_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x0000007a
  mov     x1, 0x78
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_0b_setup:
  _strb   0xdf, ATTR_T
  _strb   0x07, attributes_file + 0x00001294
  _strb   0xb8, MASK_T
  _strb   0x69, P_FLAG
  ret

po_attr_0b_setup_regs:
  ldr     x0, = display_file + 0x000284a8
  ret

po_attr_0b_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00001294
  mov     x1, 0x47
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_0b_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00001294
  mov     x1, 0x47
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_0c_setup:
  _strb   0xcd, ATTR_T
  _strb   0xb7, attributes_file + 0x00000153
  _strb   0x30, MASK_T
  _strb   0x4a, P_FLAG
  ret

po_attr_0c_setup_regs:
  ldr     x0, = display_file + 0x00002466
  ret

po_attr_0c_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000153
  mov     x1, 0xc5
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_0c_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000153
  mov     x1, 0xc5
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_0d_setup:
  _strb   0xa8, ATTR_T
  _strb   0x45, attributes_file + 0x000000f4
  _strb   0xb2, MASK_T
  _strb   0x0f, P_FLAG
  ret

po_attr_0d_setup_regs:
  ldr     x0, = display_file + 0x00004568
  ret

po_attr_0d_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000000f4
  mov     x1, 0x08
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_0d_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000000f4
  mov     x1, 0x08
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_0e_setup:
  _strb   0x11, ATTR_T
  _strb   0x85, attributes_file + 0x00000074
  _strb   0x45, MASK_T
  _strb   0x52, P_FLAG
  ret

po_attr_0e_setup_regs:
  ldr     x0, = display_file + 0x00006628
  ret

po_attr_0e_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000074
  mov     x1, 0x07
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_0e_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000074
  mov     x1, 0x07
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_0f_setup:
  _strb   0x3f, ATTR_T
  _strb   0x4d, attributes_file + 0x00000b6a
  _strb   0x6a, MASK_T
  _strb   0xd5, P_FLAG
  ret

po_attr_0f_setup_regs:
  ldr     x0, = display_file + 0x00015774
  ret

po_attr_0f_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000b6a
  mov     x1, 0x47
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_0f_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000b6a
  mov     x1, 0x47
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_10_setup:
  _strb   0x67, ATTR_T
  _strb   0x40, attributes_file + 0x00000b6d
  _strb   0xef, MASK_T
  _strb   0xed, P_FLAG
  ret

po_attr_10_setup_regs:
  ldr     x0, = display_file + 0x0001577a
  ret

po_attr_10_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000b6d
  mov     x1, 0x78
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_10_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000b6d
  mov     x1, 0x78
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_11_setup:
  _strb   0xb2, ATTR_T
  _strb   0xd3, attributes_file + 0x000000e4
  _strb   0x7e, MASK_T
  _strb   0x3c, P_FLAG
  ret

po_attr_11_setup_regs:
  ldr     x0, = display_file + 0x00003468
  ret

po_attr_11_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000000e4
  mov     x1, 0xd7
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_11_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000000e4
  mov     x1, 0xd7
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_12_setup:
  _strb   0x2d, ATTR_T
  _strb   0x90, attributes_file + 0x00001295
  _strb   0x44, MASK_T
  _strb   0x7c, P_FLAG
  ret

po_attr_12_setup_regs:
  ldr     x0, = display_file + 0x00021f6a
  ret

po_attr_12_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00001295
  mov     x1, 0x38
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_12_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00001295
  mov     x1, 0x38
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_13_setup:
  _strb   0x2d, ATTR_T
  _strb   0x09, attributes_file + 0x000011d6
  _strb   0x1c, MASK_T
  _strb   0x72, P_FLAG
  ret

po_attr_13_setup_regs:
  ldr     x0, = display_file + 0x00021dec
  ret

po_attr_13_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000011d6
  mov     x1, 0x38
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_13_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000011d6
  mov     x1, 0x38
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_14_setup:
  _strb   0x2b, ATTR_T
  _strb   0x66, attributes_file + 0x00000238
  _strb   0xe9, MASK_T
  _strb   0xa2, P_FLAG
  ret

po_attr_14_setup_regs:
  ldr     x0, = display_file + 0x00007a90
  ret

po_attr_14_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000238
  mov     x1, 0x62
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_14_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000238
  mov     x1, 0x62
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_15_setup:
  _strb   0x73, ATTR_T
  _strb   0xaa, attributes_file + 0x00000aaa
  _strb   0x20, MASK_T
  _strb   0xa8, P_FLAG
  ret

po_attr_15_setup_regs:
  ldr     x0, = display_file + 0x00018894
  ret

po_attr_15_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000aaa
  mov     x1, 0x73
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_15_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000aaa
  mov     x1, 0x73
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_16_setup:
  _strb   0xab, ATTR_T
  _strb   0x48, attributes_file + 0x00000b03
  _strb   0x71, MASK_T
  _strb   0x02, P_FLAG
  ret

po_attr_16_setup_regs:
  ldr     x0, = display_file + 0x00012406
  ret

po_attr_16_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000b03
  mov     x1, 0xca
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_16_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000b03
  mov     x1, 0xca
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_17_setup:
  _strb   0xe1, ATTR_T
  _strb   0x5f, attributes_file + 0x00001240
  _strb   0xdb, MASK_T
  _strb   0x8a, P_FLAG
  ret

po_attr_17_setup_regs:
  ldr     x0, = display_file + 0x00022fa0
  ret

po_attr_17_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00001240
  mov     x1, 0x7b
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_17_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00001240
  mov     x1, 0x7b
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_18_setup:
  _strb   0x72, ATTR_T
  _strb   0xa5, attributes_file + 0x0000095e
  _strb   0x92, MASK_T
  _strb   0x65, P_FLAG
  ret

po_attr_18_setup_regs:
  ldr     x0, = display_file + 0x0001643c
  ret

po_attr_18_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x0000095e
  mov     x1, 0xf8
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_18_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x0000095e
  mov     x1, 0xf8
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_19_setup:
  _strb   0x9d, ATTR_T
  _strb   0x93, attributes_file + 0x0000030b
  _strb   0x66, MASK_T
  _strb   0x48, P_FLAG
  ret

po_attr_19_setup_regs:
  ldr     x0, = display_file + 0x000038b6
  ret

po_attr_19_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x0000030b
  mov     x1, 0xbb
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_19_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x0000030b
  mov     x1, 0xbb
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_1a_setup:
  _strb   0x27, ATTR_T
  _strb   0x3b, attributes_file + 0x00001151
  _strb   0x56, MASK_T
  _strb   0xda, P_FLAG
  ret

po_attr_1a_setup_regs:
  ldr     x0, = display_file + 0x00026062
  ret

po_attr_1a_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00001151
  mov     x1, 0x38
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_1a_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00001151
  mov     x1, 0x38
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_1b_setup:
  _strb   0xb5, ATTR_T
  _strb   0xa1, attributes_file + 0x00000017
  _strb   0xa2, MASK_T
  _strb   0x84, P_FLAG
  ret

po_attr_1b_setup_regs:
  ldr     x0, = display_file + 0x0000764e
  ret

po_attr_1b_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000017
  mov     x1, 0xb5
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_1b_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000017
  mov     x1, 0xb5
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_1c_setup:
  _strb   0x38, ATTR_T
  _strb   0xbf, attributes_file + 0x00000aa6
  _strb   0x46, MASK_T
  _strb   0xb8, P_FLAG
  ret

po_attr_1c_setup_regs:
  ldr     x0, = display_file + 0x0001342c
  ret

po_attr_1c_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000aa6
  mov     x1, 0x38
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_1c_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000aa6
  mov     x1, 0x38
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_1d_setup:
  _strb   0x3c, ATTR_T
  _strb   0x5f, attributes_file + 0x00000b11
  _strb   0x57, MASK_T
  _strb   0x83, P_FLAG
  ret

po_attr_1d_setup_regs:
  ldr     x0, = display_file + 0x000167a2
  ret

po_attr_1d_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000b11
  mov     x1, 0x7f
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_1d_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000b11
  mov     x1, 0x7f
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_1e_setup:
  _strb   0xed, ATTR_T
  _strb   0x9e, attributes_file + 0x000000ea
  _strb   0x08, MASK_T
  _strb   0x73, P_FLAG
  ret

po_attr_1e_setup_regs:
  ldr     x0, = display_file + 0x00004554
  ret

po_attr_1e_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000000ea
  mov     x1, 0xc7
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_1e_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000000ea
  mov     x1, 0xc7
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_1f_setup:
  _strb   0x81, ATTR_T
  _strb   0x4d, attributes_file + 0x000013e9
  _strb   0x48, MASK_T
  _strb   0x1a, P_FLAG
  ret

po_attr_1f_setup_regs:
  ldr     x0, = display_file + 0x000243d2
  ret

po_attr_1f_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000013e9
  mov     x1, 0xcf
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_1f_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000013e9
  mov     x1, 0xcf
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_20_setup:
  _strb   0x7e, ATTR_T
  _strb   0xb7, attributes_file + 0x00000294
  _strb   0x5f, MASK_T
  _strb   0x5b, P_FLAG
  ret

po_attr_20_setup_regs:
  ldr     x0, = display_file + 0x00007b48
  ret

po_attr_20_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000294
  mov     x1, 0x07
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_20_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000294
  mov     x1, 0x07
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_21_setup:
  _strb   0x75, ATTR_T
  _strb   0xa6, attributes_file + 0x00000b69
  _strb   0x98, MASK_T
  _strb   0xf0, P_FLAG
  ret

po_attr_21_setup_regs:
  ldr     x0, = display_file + 0x000124d2
  ret

po_attr_21_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000b69
  mov     x1, 0xc7
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_21_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000b69
  mov     x1, 0xc7
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_22_setup:
  _strb   0x51, ATTR_T
  _strb   0x1a, attributes_file + 0x00000965
  _strb   0xf1, MASK_T
  _strb   0x7c, P_FLAG
  ret

po_attr_22_setup_regs:
  ldr     x0, = display_file + 0x0001644a
  ret

po_attr_22_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000965
  mov     x1, 0x38
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_22_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000965
  mov     x1, 0x38
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_23_setup:
  _strb   0x68, ATTR_T
  _strb   0x71, attributes_file + 0x000013d8
  _strb   0x46, MASK_T
  _strb   0x8e, P_FLAG
  ret

po_attr_23_setup_regs:
  ldr     x0, = display_file + 0x00027650
  ret

po_attr_23_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000013d8
  mov     x1, 0x68
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_23_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000013d8
  mov     x1, 0x68
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_24_setup:
  _strb   0xe7, ATTR_T
  _strb   0xc8, attributes_file + 0x00000157
  _strb   0xe8, MASK_T
  _strb   0x98, P_FLAG
  ret

po_attr_24_setup_regs:
  ldr     x0, = display_file + 0x0000570e
  ret

po_attr_24_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000157
  mov     x1, 0xcf
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_24_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000157
  mov     x1, 0xcf
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_25_setup:
  _strb   0xe7, ATTR_T
  _strb   0x5a, attributes_file + 0x000009ca
  _strb   0x21, MASK_T
  _strb   0x21, P_FLAG
  ret

po_attr_25_setup_regs:
  ldr     x0, = display_file + 0x00015434
  ret

po_attr_25_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000009ca
  mov     x1, 0xc6
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_25_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000009ca
  mov     x1, 0xc6
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_26_setup:
  _strb   0xe4, ATTR_T
  _strb   0x9a, attributes_file + 0x00001167
  _strb   0x32, MASK_T
  _strb   0x63, P_FLAG
  ret

po_attr_26_setup_regs:
  ldr     x0, = display_file + 0x00022dee
  ret

po_attr_26_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00001167
  mov     x1, 0xc6
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_26_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00001167
  mov     x1, 0xc6
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_27_setup:
  _strb   0x0f, ATTR_T
  _strb   0xa7, attributes_file + 0x000001c6
  _strb   0x0f, MASK_T
  _strb   0x7f, P_FLAG
  ret

po_attr_27_setup_regs:
  ldr     x0, = display_file + 0x0000362c
  ret

po_attr_27_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000001c6
  mov     x1, 0x07
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_27_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000001c6
  mov     x1, 0x07
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_28_setup:
  _strb   0x1f, ATTR_T
  _strb   0x75, attributes_file + 0x00000a98
  _strb   0x23, MASK_T
  _strb   0xc5, P_FLAG
  ret

po_attr_28_setup_regs:
  ldr     x0, = display_file + 0x000166b0
  ret

po_attr_28_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000a98
  mov     x1, 0x05
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_28_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000a98
  mov     x1, 0x05
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_29_setup:
  _strb   0xbf, ATTR_T
  _strb   0xb4, attributes_file + 0x0000014b
  _strb   0x28, MASK_T
  _strb   0x75, P_FLAG
  ret

po_attr_29_setup_regs:
  ldr     x0, = display_file + 0x00003536
  ret

po_attr_29_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x0000014b
  mov     x1, 0x87
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_29_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x0000014b
  mov     x1, 0x87
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_2a_setup:
  _strb   0x63, ATTR_T
  _strb   0x6e, attributes_file + 0x00000222
  _strb   0xb2, MASK_T
  _strb   0x89, P_FLAG
  ret

po_attr_2a_setup_regs:
  ldr     x0, = display_file + 0x00002604
  ret

po_attr_2a_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000222
  mov     x1, 0x63
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_2a_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000222
  mov     x1, 0x63
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_2b_setup:
  _strb   0xc3, ATTR_T
  _strb   0xe6, attributes_file + 0x000012a4
  _strb   0x47, MASK_T
  _strb   0xe2, P_FLAG
  ret

po_attr_2b_setup_regs:
  ldr     x0, = display_file + 0x000295a8
  ret

po_attr_2b_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000012a4
  mov     x1, 0xc6
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_2b_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000012a4
  mov     x1, 0xc6
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_2c_setup:
  _strb   0x5e, ATTR_T
  _strb   0x61, attributes_file + 0x00001370
  _strb   0xeb, MASK_T
  _strb   0x2f, P_FLAG
  ret

po_attr_2c_setup_regs:
  ldr     x0, = display_file + 0x000242e0
  ret

po_attr_2c_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00001370
  mov     x1, 0x75
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_2c_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00001370
  mov     x1, 0x75
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_2d_setup:
  _strb   0xa7, ATTR_T
  _strb   0xf2, attributes_file + 0x0000115f
  _strb   0x83, MASK_T
  _strb   0xc3, P_FLAG
  ret

po_attr_2d_setup_regs:
  ldr     x0, = display_file + 0x0002715e
  ret

po_attr_2d_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x0000115f
  mov     x1, 0x86
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_2d_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x0000115f
  mov     x1, 0x86
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_2e_setup:
  _strb   0xbb, ATTR_T
  _strb   0x9d, attributes_file + 0x000001c9
  _strb   0x81, MASK_T
  _strb   0x5f, P_FLAG
  ret

po_attr_2e_setup_regs:
  ldr     x0, = display_file + 0x00002552
  ret

po_attr_2e_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000001c9
  mov     x1, 0xb8
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_2e_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000001c9
  mov     x1, 0xb8
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_2f_setup:
  _strb   0x6d, ATTR_T
  _strb   0x75, attributes_file + 0x00001306
  _strb   0x63, MASK_T
  _strb   0x0d, P_FLAG
  ret

po_attr_2f_setup_regs:
  ldr     x0, = display_file + 0x000274ac
  ret

po_attr_2f_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00001306
  mov     x1, 0x6d
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_2f_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00001306
  mov     x1, 0x6d
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_30_setup:
  _strb   0x40, ATTR_T
  _strb   0x87, attributes_file + 0x00001238
  _strb   0x62, MASK_T
  _strb   0x73, P_FLAG
  ret

po_attr_30_setup_regs:
  ldr     x0, = display_file + 0x00024070
  ret

po_attr_30_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00001238
  mov     x1, 0x38
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_30_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00001238
  mov     x1, 0x38
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_31_setup:
  _strb   0xdd, ATTR_T
  _strb   0x0f, attributes_file + 0x00000b6e
  _strb   0x01, MASK_T
  _strb   0x0f, P_FLAG
  ret

po_attr_31_setup_regs:
  ldr     x0, = display_file + 0x000113fc
  ret

po_attr_31_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000b6e
  mov     x1, 0xdd
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_31_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000b6e
  mov     x1, 0xdd
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_32_setup:
  _strb   0x5e, ATTR_T
  _strb   0x8a, attributes_file + 0x000012aa
  _strb   0x5f, MASK_T
  _strb   0x18, P_FLAG
  ret

po_attr_32_setup_regs:
  ldr     x0, = display_file + 0x00021f94
  ret

po_attr_32_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000012aa
  mov     x1, 0x0f
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_32_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000012aa
  mov     x1, 0x0f
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_33_setup:
  _strb   0xb4, ATTR_T
  _strb   0xe2, attributes_file + 0x00000303
  _strb   0x84, MASK_T
  _strb   0x0c, P_FLAG
  ret

po_attr_33_setup_regs:
  ldr     x0, = display_file + 0x00004986
  ret

po_attr_33_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000303
  mov     x1, 0xb0
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_33_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000303
  mov     x1, 0xb0
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_34_setup:
  _strb   0xf6, ATTR_T
  _strb   0x4e, attributes_file + 0x000000ef
  _strb   0x8e, MASK_T
  _strb   0xa8, P_FLAG
  ret

po_attr_34_setup_regs:
  ldr     x0, = display_file + 0x0000347e
  ret

po_attr_34_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000000ef
  mov     x1, 0x7e
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_34_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000000ef
  mov     x1, 0x7e
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_35_setup:
  _strb   0xc1, ATTR_T
  _strb   0x76, attributes_file + 0x00000154
  _strb   0x4e, MASK_T
  _strb   0x65, P_FLAG
  ret

po_attr_35_setup_regs:
  ldr     x0, = display_file + 0x00001388
  ret

po_attr_35_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000154
  mov     x1, 0xc7
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_35_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000154
  mov     x1, 0xc7
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_36_setup:
  _strb   0xc4, ATTR_T
  _strb   0x6d, attributes_file + 0x0000007a
  _strb   0x8a, MASK_T
  _strb   0x99, P_FLAG
  ret

po_attr_36_setup_regs:
  ldr     x0, = display_file + 0x000022b4
  ret

po_attr_36_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x0000007a
  mov     x1, 0x4f
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_36_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x0000007a
  mov     x1, 0x4f
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_37_setup:
  _strb   0x3b, ATTR_T
  _strb   0x6d, attributes_file + 0x000010ff
  _strb   0xf2, MASK_T
  _strb   0x0e, P_FLAG
  ret

po_attr_37_setup_regs:
  ldr     x0, = display_file + 0x00021c3e
  ret

po_attr_37_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000010ff
  mov     x1, 0x69
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_37_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000010ff
  mov     x1, 0x69
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_38_setup:
  _strb   0x44, ATTR_T
  _strb   0x79, attributes_file + 0x000008f6
  _strb   0x6b, MASK_T
  _strb   0x94, P_FLAG
  ret

po_attr_38_setup_regs:
  ldr     x0, = display_file + 0x0001528c
  ret

po_attr_38_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000008f6
  mov     x1, 0x68
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_38_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000008f6
  mov     x1, 0x68
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_39_setup:
  _strb   0x5d, ATTR_T
  _strb   0x9c, attributes_file + 0x000011cd
  _strb   0xae, MASK_T
  _strb   0x9f, P_FLAG
  ret

po_attr_39_setup_regs:
  ldr     x0, = display_file + 0x0002615a
  ret

po_attr_39_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000011cd
  mov     x1, 0xdf
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_39_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000011cd
  mov     x1, 0xdf
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_3a_setup:
  _strb   0x99, ATTR_T
  _strb   0xdb, attributes_file + 0x0000130b
  _strb   0xb8, MASK_T
  _strb   0x68, P_FLAG
  ret

po_attr_3a_setup_regs:
  ldr     x0, = display_file + 0x00022056
  ret

po_attr_3a_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x0000130b
  mov     x1, 0xb9
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_3a_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x0000130b
  mov     x1, 0xb9
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_3b_setup:
  _strb   0x9d, ATTR_T
  _strb   0xc4, attributes_file + 0x000008ed
  _strb   0xf8, MASK_T
  _strb   0xb6, P_FLAG
  ret

po_attr_3b_setup_regs:
  ldr     x0, = display_file + 0x0001419a
  ret

po_attr_3b_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000008ed
  mov     x1, 0xc7
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_3b_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x000008ed
  mov     x1, 0xc7
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_3c_setup:
  _strb   0x63, ATTR_T
  _strb   0x16, attributes_file + 0x0000006d
  _strb   0xc7, MASK_T
  _strb   0x2c, P_FLAG
  ret

po_attr_3c_setup_regs:
  ldr     x0, = display_file + 0x000076fa
  ret

po_attr_3c_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x0000006d
  mov     x1, 0x26
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_3c_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x0000006d
  mov     x1, 0x26
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_3d_setup:
  _strb   0xb5, ATTR_T
  _strb   0xde, attributes_file + 0x00000228
  _strb   0xbc, MASK_T
  _strb   0xbd, P_FLAG
  ret

po_attr_3d_setup_regs:
  ldr     x0, = display_file + 0x000058b0
  ret

po_attr_3d_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000228
  mov     x1, 0x9f
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_3d_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000228
  mov     x1, 0x9f
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_3e_setup:
  _strb   0x78, ATTR_T
  _strb   0x50, attributes_file + 0x00000153
  _strb   0xb7, MASK_T
  _strb   0xac, P_FLAG
  ret

po_attr_3e_setup_regs:
  ldr     x0, = display_file + 0x000078c6
  ret

po_attr_3e_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000153
  mov     x1, 0x58
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_3e_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000153
  mov     x1, 0x58
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret


po_attr_3f_setup:
  _strb   0xca, ATTR_T
  _strb   0x1e, attributes_file + 0x00000a27
  _strb   0x12, MASK_T
  _strb   0x92, P_FLAG
  ret

po_attr_3f_setup_regs:
  ldr     x0, = display_file + 0x0001878e
  ret

po_attr_3f_effects:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000a27
  mov     x1, 0xdf
  bl      poke_address
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret

po_attr_3f_effects_regs:
  stp     x29, x30, [sp, #-16]!                   // Push frame pointer, procedure link register on stack.
  mov     x29, sp                                 // Update frame pointer to new stack location.
  ldr     x0, = attributes_file + 0x00000a27
  mov     x1, 0xdf
  bl      poke_address
  ldr     x24, = attributes_file
  ldp     x29, x30, [sp], #0x10                   // Pop frame pointer, procedure link register off stack.
  ret
