# This file is part of the Spectrum +4 Project.
# Licencing information can be found in the LICENCE file
# (C) 2021 Spectrum +4 Authors. All rights reserved.

# This file is auto-generated by test_po_mosaic_half.sh. DO NOT EDIT!

.text

po_mosaic_half_0x00_setup_regs:
  mov     w3, 0x00
  adr     x6, display_file
  ret

po_mosaic_half_0x00_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x00_effects_regs:
  mov     w3, #0x00
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x01_setup_regs:
  mov     w3, 0x01
  adr     x6, display_file
  ret

po_mosaic_half_0x01_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x01_effects_regs:
  mov     w3, #0x00
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x02_setup_regs:
  mov     w3, 0x02
  adr     x6, display_file
  ret

po_mosaic_half_0x02_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x02_effects_regs:
  mov     w3, #0x00
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x03_setup_regs:
  mov     w3, 0x03
  adr     x6, display_file
  ret

po_mosaic_half_0x03_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x03_effects_regs:
  mov     w3, #0x00
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x04_setup_regs:
  mov     w3, 0x04
  adr     x6, display_file
  ret

po_mosaic_half_0x04_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x04_effects_regs:
  mov     w3, #0x01
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x05_setup_regs:
  mov     w3, 0x05
  adr     x6, display_file
  ret

po_mosaic_half_0x05_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x05_effects_regs:
  mov     w3, #0x01
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x06_setup_regs:
  mov     w3, 0x06
  adr     x6, display_file
  ret

po_mosaic_half_0x06_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x06_effects_regs:
  mov     w3, #0x01
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x07_setup_regs:
  mov     w3, 0x07
  adr     x6, display_file
  ret

po_mosaic_half_0x07_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x07_effects_regs:
  mov     w3, #0x01
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x08_setup_regs:
  mov     w3, 0x08
  adr     x6, display_file
  ret

po_mosaic_half_0x08_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x08_effects_regs:
  mov     w3, #0x02
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x09_setup_regs:
  mov     w3, 0x09
  adr     x6, display_file
  ret

po_mosaic_half_0x09_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x09_effects_regs:
  mov     w3, #0x02
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x0a_setup_regs:
  mov     w3, 0x0a
  adr     x6, display_file
  ret

po_mosaic_half_0x0a_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x0a_effects_regs:
  mov     w3, #0x02
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x0b_setup_regs:
  mov     w3, 0x0b
  adr     x6, display_file
  ret

po_mosaic_half_0x0b_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x0b_effects_regs:
  mov     w3, #0x02
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x0c_setup_regs:
  mov     w3, 0x0c
  adr     x6, display_file
  ret

po_mosaic_half_0x0c_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x0c_effects_regs:
  mov     w3, #0x03
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x0d_setup_regs:
  mov     w3, 0x0d
  adr     x6, display_file
  ret

po_mosaic_half_0x0d_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x0d_effects_regs:
  mov     w3, #0x03
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x0e_setup_regs:
  mov     w3, 0x0e
  adr     x6, display_file
  ret

po_mosaic_half_0x0e_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x0e_effects_regs:
  mov     w3, #0x03
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x0f_setup_regs:
  mov     w3, 0x0f
  adr     x6, display_file
  ret

po_mosaic_half_0x0f_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x0f_effects_regs:
  mov     w3, #0x03
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x10_setup_regs:
  mov     w3, 0x10
  adr     x6, display_file
  ret

po_mosaic_half_0x10_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x10_effects_regs:
  mov     w3, #0x04
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x11_setup_regs:
  mov     w3, 0x11
  adr     x6, display_file
  ret

po_mosaic_half_0x11_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x11_effects_regs:
  mov     w3, #0x04
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x12_setup_regs:
  mov     w3, 0x12
  adr     x6, display_file
  ret

po_mosaic_half_0x12_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x12_effects_regs:
  mov     w3, #0x04
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x13_setup_regs:
  mov     w3, 0x13
  adr     x6, display_file
  ret

po_mosaic_half_0x13_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x13_effects_regs:
  mov     w3, #0x04
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x14_setup_regs:
  mov     w3, 0x14
  adr     x6, display_file
  ret

po_mosaic_half_0x14_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x14_effects_regs:
  mov     w3, #0x05
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x15_setup_regs:
  mov     w3, 0x15
  adr     x6, display_file
  ret

po_mosaic_half_0x15_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x15_effects_regs:
  mov     w3, #0x05
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x16_setup_regs:
  mov     w3, 0x16
  adr     x6, display_file
  ret

po_mosaic_half_0x16_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x16_effects_regs:
  mov     w3, #0x05
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x17_setup_regs:
  mov     w3, 0x17
  adr     x6, display_file
  ret

po_mosaic_half_0x17_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x17_effects_regs:
  mov     w3, #0x05
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x18_setup_regs:
  mov     w3, 0x18
  adr     x6, display_file
  ret

po_mosaic_half_0x18_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x18_effects_regs:
  mov     w3, #0x06
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x19_setup_regs:
  mov     w3, 0x19
  adr     x6, display_file
  ret

po_mosaic_half_0x19_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x19_effects_regs:
  mov     w3, #0x06
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x1a_setup_regs:
  mov     w3, 0x1a
  adr     x6, display_file
  ret

po_mosaic_half_0x1a_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x1a_effects_regs:
  mov     w3, #0x06
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x1b_setup_regs:
  mov     w3, 0x1b
  adr     x6, display_file
  ret

po_mosaic_half_0x1b_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x1b_effects_regs:
  mov     w3, #0x06
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x1c_setup_regs:
  mov     w3, 0x1c
  adr     x6, display_file
  ret

po_mosaic_half_0x1c_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x1c_effects_regs:
  mov     w3, #0x07
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x1d_setup_regs:
  mov     w3, 0x1d
  adr     x6, display_file
  ret

po_mosaic_half_0x1d_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x1d_effects_regs:
  mov     w3, #0x07
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x1e_setup_regs:
  mov     w3, 0x1e
  adr     x6, display_file
  ret

po_mosaic_half_0x1e_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x1e_effects_regs:
  mov     w3, #0x07
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x1f_setup_regs:
  mov     w3, 0x1f
  adr     x6, display_file
  ret

po_mosaic_half_0x1f_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x1f_effects_regs:
  mov     w3, #0x07
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x20_setup_regs:
  mov     w3, 0x20
  adr     x6, display_file
  ret

po_mosaic_half_0x20_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x20_effects_regs:
  mov     w3, #0x08
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x21_setup_regs:
  mov     w3, 0x21
  adr     x6, display_file
  ret

po_mosaic_half_0x21_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x21_effects_regs:
  mov     w3, #0x08
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x22_setup_regs:
  mov     w3, 0x22
  adr     x6, display_file
  ret

po_mosaic_half_0x22_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x22_effects_regs:
  mov     w3, #0x08
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x23_setup_regs:
  mov     w3, 0x23
  adr     x6, display_file
  ret

po_mosaic_half_0x23_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x23_effects_regs:
  mov     w3, #0x08
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x24_setup_regs:
  mov     w3, 0x24
  adr     x6, display_file
  ret

po_mosaic_half_0x24_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x24_effects_regs:
  mov     w3, #0x09
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x25_setup_regs:
  mov     w3, 0x25
  adr     x6, display_file
  ret

po_mosaic_half_0x25_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x25_effects_regs:
  mov     w3, #0x09
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x26_setup_regs:
  mov     w3, 0x26
  adr     x6, display_file
  ret

po_mosaic_half_0x26_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x26_effects_regs:
  mov     w3, #0x09
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x27_setup_regs:
  mov     w3, 0x27
  adr     x6, display_file
  ret

po_mosaic_half_0x27_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x27_effects_regs:
  mov     w3, #0x09
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x28_setup_regs:
  mov     w3, 0x28
  adr     x6, display_file
  ret

po_mosaic_half_0x28_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x28_effects_regs:
  mov     w3, #0x0a
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x29_setup_regs:
  mov     w3, 0x29
  adr     x6, display_file
  ret

po_mosaic_half_0x29_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x29_effects_regs:
  mov     w3, #0x0a
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x2a_setup_regs:
  mov     w3, 0x2a
  adr     x6, display_file
  ret

po_mosaic_half_0x2a_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x2a_effects_regs:
  mov     w3, #0x0a
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x2b_setup_regs:
  mov     w3, 0x2b
  adr     x6, display_file
  ret

po_mosaic_half_0x2b_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x2b_effects_regs:
  mov     w3, #0x0a
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x2c_setup_regs:
  mov     w3, 0x2c
  adr     x6, display_file
  ret

po_mosaic_half_0x2c_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x2c_effects_regs:
  mov     w3, #0x0b
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x2d_setup_regs:
  mov     w3, 0x2d
  adr     x6, display_file
  ret

po_mosaic_half_0x2d_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x2d_effects_regs:
  mov     w3, #0x0b
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x2e_setup_regs:
  mov     w3, 0x2e
  adr     x6, display_file
  ret

po_mosaic_half_0x2e_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x2e_effects_regs:
  mov     w3, #0x0b
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x2f_setup_regs:
  mov     w3, 0x2f
  adr     x6, display_file
  ret

po_mosaic_half_0x2f_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x2f_effects_regs:
  mov     w3, #0x0b
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x30_setup_regs:
  mov     w3, 0x30
  adr     x6, display_file
  ret

po_mosaic_half_0x30_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x30_effects_regs:
  mov     w3, #0x0c
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x31_setup_regs:
  mov     w3, 0x31
  adr     x6, display_file
  ret

po_mosaic_half_0x31_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x31_effects_regs:
  mov     w3, #0x0c
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x32_setup_regs:
  mov     w3, 0x32
  adr     x6, display_file
  ret

po_mosaic_half_0x32_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x32_effects_regs:
  mov     w3, #0x0c
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x33_setup_regs:
  mov     w3, 0x33
  adr     x6, display_file
  ret

po_mosaic_half_0x33_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x33_effects_regs:
  mov     w3, #0x0c
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x34_setup_regs:
  mov     w3, 0x34
  adr     x6, display_file
  ret

po_mosaic_half_0x34_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x34_effects_regs:
  mov     w3, #0x0d
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x35_setup_regs:
  mov     w3, 0x35
  adr     x6, display_file
  ret

po_mosaic_half_0x35_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x35_effects_regs:
  mov     w3, #0x0d
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x36_setup_regs:
  mov     w3, 0x36
  adr     x6, display_file
  ret

po_mosaic_half_0x36_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x36_effects_regs:
  mov     w3, #0x0d
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x37_setup_regs:
  mov     w3, 0x37
  adr     x6, display_file
  ret

po_mosaic_half_0x37_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x37_effects_regs:
  mov     w3, #0x0d
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x38_setup_regs:
  mov     w3, 0x38
  adr     x6, display_file
  ret

po_mosaic_half_0x38_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x38_effects_regs:
  mov     w3, #0x0e
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x39_setup_regs:
  mov     w3, 0x39
  adr     x6, display_file
  ret

po_mosaic_half_0x39_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x39_effects_regs:
  mov     w3, #0x0e
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x3a_setup_regs:
  mov     w3, 0x3a
  adr     x6, display_file
  ret

po_mosaic_half_0x3a_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x3a_effects_regs:
  mov     w3, #0x0e
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x3b_setup_regs:
  mov     w3, 0x3b
  adr     x6, display_file
  ret

po_mosaic_half_0x3b_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x3b_effects_regs:
  mov     w3, #0x0e
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x3c_setup_regs:
  mov     w3, 0x3c
  adr     x6, display_file
  ret

po_mosaic_half_0x3c_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x3c_effects_regs:
  mov     w3, #0x0f
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x3d_setup_regs:
  mov     w3, 0x3d
  adr     x6, display_file
  ret

po_mosaic_half_0x3d_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x3d_effects_regs:
  mov     w3, #0x0f
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x3e_setup_regs:
  mov     w3, 0x3e
  adr     x6, display_file
  ret

po_mosaic_half_0x3e_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x3e_effects_regs:
  mov     w3, #0x0f
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x3f_setup_regs:
  mov     w3, 0x3f
  adr     x6, display_file
  ret

po_mosaic_half_0x3f_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x3f_effects_regs:
  mov     w3, #0x0f
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x40_setup_regs:
  mov     w3, 0x40
  adr     x6, display_file
  ret

po_mosaic_half_0x40_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x40_effects_regs:
  mov     w3, #0x10
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x41_setup_regs:
  mov     w3, 0x41
  adr     x6, display_file
  ret

po_mosaic_half_0x41_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x41_effects_regs:
  mov     w3, #0x10
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x42_setup_regs:
  mov     w3, 0x42
  adr     x6, display_file
  ret

po_mosaic_half_0x42_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x42_effects_regs:
  mov     w3, #0x10
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x43_setup_regs:
  mov     w3, 0x43
  adr     x6, display_file
  ret

po_mosaic_half_0x43_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x43_effects_regs:
  mov     w3, #0x10
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x44_setup_regs:
  mov     w3, 0x44
  adr     x6, display_file
  ret

po_mosaic_half_0x44_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x44_effects_regs:
  mov     w3, #0x11
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x45_setup_regs:
  mov     w3, 0x45
  adr     x6, display_file
  ret

po_mosaic_half_0x45_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x45_effects_regs:
  mov     w3, #0x11
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x46_setup_regs:
  mov     w3, 0x46
  adr     x6, display_file
  ret

po_mosaic_half_0x46_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x46_effects_regs:
  mov     w3, #0x11
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x47_setup_regs:
  mov     w3, 0x47
  adr     x6, display_file
  ret

po_mosaic_half_0x47_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x47_effects_regs:
  mov     w3, #0x11
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x48_setup_regs:
  mov     w3, 0x48
  adr     x6, display_file
  ret

po_mosaic_half_0x48_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x48_effects_regs:
  mov     w3, #0x12
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x49_setup_regs:
  mov     w3, 0x49
  adr     x6, display_file
  ret

po_mosaic_half_0x49_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x49_effects_regs:
  mov     w3, #0x12
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x4a_setup_regs:
  mov     w3, 0x4a
  adr     x6, display_file
  ret

po_mosaic_half_0x4a_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x4a_effects_regs:
  mov     w3, #0x12
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x4b_setup_regs:
  mov     w3, 0x4b
  adr     x6, display_file
  ret

po_mosaic_half_0x4b_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x4b_effects_regs:
  mov     w3, #0x12
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x4c_setup_regs:
  mov     w3, 0x4c
  adr     x6, display_file
  ret

po_mosaic_half_0x4c_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x4c_effects_regs:
  mov     w3, #0x13
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x4d_setup_regs:
  mov     w3, 0x4d
  adr     x6, display_file
  ret

po_mosaic_half_0x4d_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x4d_effects_regs:
  mov     w3, #0x13
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x4e_setup_regs:
  mov     w3, 0x4e
  adr     x6, display_file
  ret

po_mosaic_half_0x4e_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x4e_effects_regs:
  mov     w3, #0x13
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x4f_setup_regs:
  mov     w3, 0x4f
  adr     x6, display_file
  ret

po_mosaic_half_0x4f_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x4f_effects_regs:
  mov     w3, #0x13
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x50_setup_regs:
  mov     w3, 0x50
  adr     x6, display_file
  ret

po_mosaic_half_0x50_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x50_effects_regs:
  mov     w3, #0x14
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x51_setup_regs:
  mov     w3, 0x51
  adr     x6, display_file
  ret

po_mosaic_half_0x51_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x51_effects_regs:
  mov     w3, #0x14
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x52_setup_regs:
  mov     w3, 0x52
  adr     x6, display_file
  ret

po_mosaic_half_0x52_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x52_effects_regs:
  mov     w3, #0x14
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x53_setup_regs:
  mov     w3, 0x53
  adr     x6, display_file
  ret

po_mosaic_half_0x53_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x53_effects_regs:
  mov     w3, #0x14
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x54_setup_regs:
  mov     w3, 0x54
  adr     x6, display_file
  ret

po_mosaic_half_0x54_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x54_effects_regs:
  mov     w3, #0x15
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x55_setup_regs:
  mov     w3, 0x55
  adr     x6, display_file
  ret

po_mosaic_half_0x55_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x55_effects_regs:
  mov     w3, #0x15
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x56_setup_regs:
  mov     w3, 0x56
  adr     x6, display_file
  ret

po_mosaic_half_0x56_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x56_effects_regs:
  mov     w3, #0x15
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x57_setup_regs:
  mov     w3, 0x57
  adr     x6, display_file
  ret

po_mosaic_half_0x57_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x57_effects_regs:
  mov     w3, #0x15
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x58_setup_regs:
  mov     w3, 0x58
  adr     x6, display_file
  ret

po_mosaic_half_0x58_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x58_effects_regs:
  mov     w3, #0x16
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x59_setup_regs:
  mov     w3, 0x59
  adr     x6, display_file
  ret

po_mosaic_half_0x59_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x59_effects_regs:
  mov     w3, #0x16
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x5a_setup_regs:
  mov     w3, 0x5a
  adr     x6, display_file
  ret

po_mosaic_half_0x5a_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x5a_effects_regs:
  mov     w3, #0x16
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x5b_setup_regs:
  mov     w3, 0x5b
  adr     x6, display_file
  ret

po_mosaic_half_0x5b_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x5b_effects_regs:
  mov     w3, #0x16
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x5c_setup_regs:
  mov     w3, 0x5c
  adr     x6, display_file
  ret

po_mosaic_half_0x5c_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x5c_effects_regs:
  mov     w3, #0x17
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x5d_setup_regs:
  mov     w3, 0x5d
  adr     x6, display_file
  ret

po_mosaic_half_0x5d_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x5d_effects_regs:
  mov     w3, #0x17
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x5e_setup_regs:
  mov     w3, 0x5e
  adr     x6, display_file
  ret

po_mosaic_half_0x5e_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x5e_effects_regs:
  mov     w3, #0x17
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x5f_setup_regs:
  mov     w3, 0x5f
  adr     x6, display_file
  ret

po_mosaic_half_0x5f_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x5f_effects_regs:
  mov     w3, #0x17
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x60_setup_regs:
  mov     w3, 0x60
  adr     x6, display_file
  ret

po_mosaic_half_0x60_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x60_effects_regs:
  mov     w3, #0x18
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x61_setup_regs:
  mov     w3, 0x61
  adr     x6, display_file
  ret

po_mosaic_half_0x61_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x61_effects_regs:
  mov     w3, #0x18
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x62_setup_regs:
  mov     w3, 0x62
  adr     x6, display_file
  ret

po_mosaic_half_0x62_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x62_effects_regs:
  mov     w3, #0x18
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x63_setup_regs:
  mov     w3, 0x63
  adr     x6, display_file
  ret

po_mosaic_half_0x63_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x63_effects_regs:
  mov     w3, #0x18
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x64_setup_regs:
  mov     w3, 0x64
  adr     x6, display_file
  ret

po_mosaic_half_0x64_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x64_effects_regs:
  mov     w3, #0x19
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x65_setup_regs:
  mov     w3, 0x65
  adr     x6, display_file
  ret

po_mosaic_half_0x65_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x65_effects_regs:
  mov     w3, #0x19
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x66_setup_regs:
  mov     w3, 0x66
  adr     x6, display_file
  ret

po_mosaic_half_0x66_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x66_effects_regs:
  mov     w3, #0x19
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x67_setup_regs:
  mov     w3, 0x67
  adr     x6, display_file
  ret

po_mosaic_half_0x67_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x67_effects_regs:
  mov     w3, #0x19
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x68_setup_regs:
  mov     w3, 0x68
  adr     x6, display_file
  ret

po_mosaic_half_0x68_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x68_effects_regs:
  mov     w3, #0x1a
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x69_setup_regs:
  mov     w3, 0x69
  adr     x6, display_file
  ret

po_mosaic_half_0x69_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x69_effects_regs:
  mov     w3, #0x1a
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x6a_setup_regs:
  mov     w3, 0x6a
  adr     x6, display_file
  ret

po_mosaic_half_0x6a_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x6a_effects_regs:
  mov     w3, #0x1a
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x6b_setup_regs:
  mov     w3, 0x6b
  adr     x6, display_file
  ret

po_mosaic_half_0x6b_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x6b_effects_regs:
  mov     w3, #0x1a
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x6c_setup_regs:
  mov     w3, 0x6c
  adr     x6, display_file
  ret

po_mosaic_half_0x6c_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x6c_effects_regs:
  mov     w3, #0x1b
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x6d_setup_regs:
  mov     w3, 0x6d
  adr     x6, display_file
  ret

po_mosaic_half_0x6d_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x6d_effects_regs:
  mov     w3, #0x1b
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x6e_setup_regs:
  mov     w3, 0x6e
  adr     x6, display_file
  ret

po_mosaic_half_0x6e_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x6e_effects_regs:
  mov     w3, #0x1b
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x6f_setup_regs:
  mov     w3, 0x6f
  adr     x6, display_file
  ret

po_mosaic_half_0x6f_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x6f_effects_regs:
  mov     w3, #0x1b
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x70_setup_regs:
  mov     w3, 0x70
  adr     x6, display_file
  ret

po_mosaic_half_0x70_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x70_effects_regs:
  mov     w3, #0x1c
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x71_setup_regs:
  mov     w3, 0x71
  adr     x6, display_file
  ret

po_mosaic_half_0x71_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x71_effects_regs:
  mov     w3, #0x1c
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x72_setup_regs:
  mov     w3, 0x72
  adr     x6, display_file
  ret

po_mosaic_half_0x72_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x72_effects_regs:
  mov     w3, #0x1c
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x73_setup_regs:
  mov     w3, 0x73
  adr     x6, display_file
  ret

po_mosaic_half_0x73_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x73_effects_regs:
  mov     w3, #0x1c
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x74_setup_regs:
  mov     w3, 0x74
  adr     x6, display_file
  ret

po_mosaic_half_0x74_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x74_effects_regs:
  mov     w3, #0x1d
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x75_setup_regs:
  mov     w3, 0x75
  adr     x6, display_file
  ret

po_mosaic_half_0x75_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x75_effects_regs:
  mov     w3, #0x1d
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x76_setup_regs:
  mov     w3, 0x76
  adr     x6, display_file
  ret

po_mosaic_half_0x76_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x76_effects_regs:
  mov     w3, #0x1d
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x77_setup_regs:
  mov     w3, 0x77
  adr     x6, display_file
  ret

po_mosaic_half_0x77_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x77_effects_regs:
  mov     w3, #0x1d
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x78_setup_regs:
  mov     w3, 0x78
  adr     x6, display_file
  ret

po_mosaic_half_0x78_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x78_effects_regs:
  mov     w3, #0x1e
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x79_setup_regs:
  mov     w3, 0x79
  adr     x6, display_file
  ret

po_mosaic_half_0x79_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x79_effects_regs:
  mov     w3, #0x1e
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x7a_setup_regs:
  mov     w3, 0x7a
  adr     x6, display_file
  ret

po_mosaic_half_0x7a_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x7a_effects_regs:
  mov     w3, #0x1e
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x7b_setup_regs:
  mov     w3, 0x7b
  adr     x6, display_file
  ret

po_mosaic_half_0x7b_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x7b_effects_regs:
  mov     w3, #0x1e
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x7c_setup_regs:
  mov     w3, 0x7c
  adr     x6, display_file
  ret

po_mosaic_half_0x7c_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x7c_effects_regs:
  mov     w3, #0x1f
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x7d_setup_regs:
  mov     w3, 0x7d
  adr     x6, display_file
  ret

po_mosaic_half_0x7d_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x7d_effects_regs:
  mov     w3, #0x1f
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x7e_setup_regs:
  mov     w3, 0x7e
  adr     x6, display_file
  ret

po_mosaic_half_0x7e_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x7e_effects_regs:
  mov     w3, #0x1f
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x7f_setup_regs:
  mov     w3, 0x7f
  adr     x6, display_file
  ret

po_mosaic_half_0x7f_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x7f_effects_regs:
  mov     w3, #0x1f
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x80_setup_regs:
  mov     w3, 0x80
  adr     x6, display_file
  ret

po_mosaic_half_0x80_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x80_effects_regs:
  mov     w3, #0x20
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x81_setup_regs:
  mov     w3, 0x81
  adr     x6, display_file
  ret

po_mosaic_half_0x81_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x81_effects_regs:
  mov     w3, #0x20
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x82_setup_regs:
  mov     w3, 0x82
  adr     x6, display_file
  ret

po_mosaic_half_0x82_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x82_effects_regs:
  mov     w3, #0x20
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x83_setup_regs:
  mov     w3, 0x83
  adr     x6, display_file
  ret

po_mosaic_half_0x83_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x83_effects_regs:
  mov     w3, #0x20
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x84_setup_regs:
  mov     w3, 0x84
  adr     x6, display_file
  ret

po_mosaic_half_0x84_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x84_effects_regs:
  mov     w3, #0x21
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x85_setup_regs:
  mov     w3, 0x85
  adr     x6, display_file
  ret

po_mosaic_half_0x85_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x85_effects_regs:
  mov     w3, #0x21
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x86_setup_regs:
  mov     w3, 0x86
  adr     x6, display_file
  ret

po_mosaic_half_0x86_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x86_effects_regs:
  mov     w3, #0x21
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x87_setup_regs:
  mov     w3, 0x87
  adr     x6, display_file
  ret

po_mosaic_half_0x87_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x87_effects_regs:
  mov     w3, #0x21
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x88_setup_regs:
  mov     w3, 0x88
  adr     x6, display_file
  ret

po_mosaic_half_0x88_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x88_effects_regs:
  mov     w3, #0x22
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x89_setup_regs:
  mov     w3, 0x89
  adr     x6, display_file
  ret

po_mosaic_half_0x89_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x89_effects_regs:
  mov     w3, #0x22
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x8a_setup_regs:
  mov     w3, 0x8a
  adr     x6, display_file
  ret

po_mosaic_half_0x8a_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x8a_effects_regs:
  mov     w3, #0x22
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x8b_setup_regs:
  mov     w3, 0x8b
  adr     x6, display_file
  ret

po_mosaic_half_0x8b_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x8b_effects_regs:
  mov     w3, #0x22
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x8c_setup_regs:
  mov     w3, 0x8c
  adr     x6, display_file
  ret

po_mosaic_half_0x8c_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x8c_effects_regs:
  mov     w3, #0x23
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x8d_setup_regs:
  mov     w3, 0x8d
  adr     x6, display_file
  ret

po_mosaic_half_0x8d_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x8d_effects_regs:
  mov     w3, #0x23
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x8e_setup_regs:
  mov     w3, 0x8e
  adr     x6, display_file
  ret

po_mosaic_half_0x8e_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x8e_effects_regs:
  mov     w3, #0x23
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x8f_setup_regs:
  mov     w3, 0x8f
  adr     x6, display_file
  ret

po_mosaic_half_0x8f_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x8f_effects_regs:
  mov     w3, #0x23
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x90_setup_regs:
  mov     w3, 0x90
  adr     x6, display_file
  ret

po_mosaic_half_0x90_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x90_effects_regs:
  mov     w3, #0x24
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x91_setup_regs:
  mov     w3, 0x91
  adr     x6, display_file
  ret

po_mosaic_half_0x91_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x91_effects_regs:
  mov     w3, #0x24
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x92_setup_regs:
  mov     w3, 0x92
  adr     x6, display_file
  ret

po_mosaic_half_0x92_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x92_effects_regs:
  mov     w3, #0x24
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x93_setup_regs:
  mov     w3, 0x93
  adr     x6, display_file
  ret

po_mosaic_half_0x93_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x93_effects_regs:
  mov     w3, #0x24
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x94_setup_regs:
  mov     w3, 0x94
  adr     x6, display_file
  ret

po_mosaic_half_0x94_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x94_effects_regs:
  mov     w3, #0x25
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x95_setup_regs:
  mov     w3, 0x95
  adr     x6, display_file
  ret

po_mosaic_half_0x95_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x95_effects_regs:
  mov     w3, #0x25
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x96_setup_regs:
  mov     w3, 0x96
  adr     x6, display_file
  ret

po_mosaic_half_0x96_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x96_effects_regs:
  mov     w3, #0x25
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x97_setup_regs:
  mov     w3, 0x97
  adr     x6, display_file
  ret

po_mosaic_half_0x97_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x97_effects_regs:
  mov     w3, #0x25
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x98_setup_regs:
  mov     w3, 0x98
  adr     x6, display_file
  ret

po_mosaic_half_0x98_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x98_effects_regs:
  mov     w3, #0x26
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x99_setup_regs:
  mov     w3, 0x99
  adr     x6, display_file
  ret

po_mosaic_half_0x99_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x99_effects_regs:
  mov     w3, #0x26
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x9a_setup_regs:
  mov     w3, 0x9a
  adr     x6, display_file
  ret

po_mosaic_half_0x9a_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x9a_effects_regs:
  mov     w3, #0x26
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x9b_setup_regs:
  mov     w3, 0x9b
  adr     x6, display_file
  ret

po_mosaic_half_0x9b_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x9b_effects_regs:
  mov     w3, #0x26
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x9c_setup_regs:
  mov     w3, 0x9c
  adr     x6, display_file
  ret

po_mosaic_half_0x9c_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0x9c_effects_regs:
  mov     w3, #0x27
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x9d_setup_regs:
  mov     w3, 0x9d
  adr     x6, display_file
  ret

po_mosaic_half_0x9d_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0x9d_effects_regs:
  mov     w3, #0x27
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0x9e_setup_regs:
  mov     w3, 0x9e
  adr     x6, display_file
  ret

po_mosaic_half_0x9e_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0x9e_effects_regs:
  mov     w3, #0x27
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0x9f_setup_regs:
  mov     w3, 0x9f
  adr     x6, display_file
  ret

po_mosaic_half_0x9f_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0x9f_effects_regs:
  mov     w3, #0x27
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xa0_setup_regs:
  mov     w3, 0xa0
  adr     x6, display_file
  ret

po_mosaic_half_0xa0_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xa0_effects_regs:
  mov     w3, #0x28
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xa1_setup_regs:
  mov     w3, 0xa1
  adr     x6, display_file
  ret

po_mosaic_half_0xa1_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xa1_effects_regs:
  mov     w3, #0x28
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xa2_setup_regs:
  mov     w3, 0xa2
  adr     x6, display_file
  ret

po_mosaic_half_0xa2_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xa2_effects_regs:
  mov     w3, #0x28
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xa3_setup_regs:
  mov     w3, 0xa3
  adr     x6, display_file
  ret

po_mosaic_half_0xa3_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xa3_effects_regs:
  mov     w3, #0x28
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xa4_setup_regs:
  mov     w3, 0xa4
  adr     x6, display_file
  ret

po_mosaic_half_0xa4_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xa4_effects_regs:
  mov     w3, #0x29
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xa5_setup_regs:
  mov     w3, 0xa5
  adr     x6, display_file
  ret

po_mosaic_half_0xa5_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xa5_effects_regs:
  mov     w3, #0x29
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xa6_setup_regs:
  mov     w3, 0xa6
  adr     x6, display_file
  ret

po_mosaic_half_0xa6_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xa6_effects_regs:
  mov     w3, #0x29
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xa7_setup_regs:
  mov     w3, 0xa7
  adr     x6, display_file
  ret

po_mosaic_half_0xa7_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xa7_effects_regs:
  mov     w3, #0x29
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xa8_setup_regs:
  mov     w3, 0xa8
  adr     x6, display_file
  ret

po_mosaic_half_0xa8_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xa8_effects_regs:
  mov     w3, #0x2a
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xa9_setup_regs:
  mov     w3, 0xa9
  adr     x6, display_file
  ret

po_mosaic_half_0xa9_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xa9_effects_regs:
  mov     w3, #0x2a
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xaa_setup_regs:
  mov     w3, 0xaa
  adr     x6, display_file
  ret

po_mosaic_half_0xaa_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xaa_effects_regs:
  mov     w3, #0x2a
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xab_setup_regs:
  mov     w3, 0xab
  adr     x6, display_file
  ret

po_mosaic_half_0xab_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xab_effects_regs:
  mov     w3, #0x2a
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xac_setup_regs:
  mov     w3, 0xac
  adr     x6, display_file
  ret

po_mosaic_half_0xac_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xac_effects_regs:
  mov     w3, #0x2b
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xad_setup_regs:
  mov     w3, 0xad
  adr     x6, display_file
  ret

po_mosaic_half_0xad_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xad_effects_regs:
  mov     w3, #0x2b
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xae_setup_regs:
  mov     w3, 0xae
  adr     x6, display_file
  ret

po_mosaic_half_0xae_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xae_effects_regs:
  mov     w3, #0x2b
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xaf_setup_regs:
  mov     w3, 0xaf
  adr     x6, display_file
  ret

po_mosaic_half_0xaf_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xaf_effects_regs:
  mov     w3, #0x2b
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xb0_setup_regs:
  mov     w3, 0xb0
  adr     x6, display_file
  ret

po_mosaic_half_0xb0_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xb0_effects_regs:
  mov     w3, #0x2c
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xb1_setup_regs:
  mov     w3, 0xb1
  adr     x6, display_file
  ret

po_mosaic_half_0xb1_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xb1_effects_regs:
  mov     w3, #0x2c
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xb2_setup_regs:
  mov     w3, 0xb2
  adr     x6, display_file
  ret

po_mosaic_half_0xb2_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xb2_effects_regs:
  mov     w3, #0x2c
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xb3_setup_regs:
  mov     w3, 0xb3
  adr     x6, display_file
  ret

po_mosaic_half_0xb3_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xb3_effects_regs:
  mov     w3, #0x2c
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xb4_setup_regs:
  mov     w3, 0xb4
  adr     x6, display_file
  ret

po_mosaic_half_0xb4_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xb4_effects_regs:
  mov     w3, #0x2d
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xb5_setup_regs:
  mov     w3, 0xb5
  adr     x6, display_file
  ret

po_mosaic_half_0xb5_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xb5_effects_regs:
  mov     w3, #0x2d
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xb6_setup_regs:
  mov     w3, 0xb6
  adr     x6, display_file
  ret

po_mosaic_half_0xb6_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xb6_effects_regs:
  mov     w3, #0x2d
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xb7_setup_regs:
  mov     w3, 0xb7
  adr     x6, display_file
  ret

po_mosaic_half_0xb7_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xb7_effects_regs:
  mov     w3, #0x2d
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xb8_setup_regs:
  mov     w3, 0xb8
  adr     x6, display_file
  ret

po_mosaic_half_0xb8_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xb8_effects_regs:
  mov     w3, #0x2e
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xb9_setup_regs:
  mov     w3, 0xb9
  adr     x6, display_file
  ret

po_mosaic_half_0xb9_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xb9_effects_regs:
  mov     w3, #0x2e
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xba_setup_regs:
  mov     w3, 0xba
  adr     x6, display_file
  ret

po_mosaic_half_0xba_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xba_effects_regs:
  mov     w3, #0x2e
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xbb_setup_regs:
  mov     w3, 0xbb
  adr     x6, display_file
  ret

po_mosaic_half_0xbb_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xbb_effects_regs:
  mov     w3, #0x2e
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xbc_setup_regs:
  mov     w3, 0xbc
  adr     x6, display_file
  ret

po_mosaic_half_0xbc_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xbc_effects_regs:
  mov     w3, #0x2f
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xbd_setup_regs:
  mov     w3, 0xbd
  adr     x6, display_file
  ret

po_mosaic_half_0xbd_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xbd_effects_regs:
  mov     w3, #0x2f
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xbe_setup_regs:
  mov     w3, 0xbe
  adr     x6, display_file
  ret

po_mosaic_half_0xbe_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xbe_effects_regs:
  mov     w3, #0x2f
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xbf_setup_regs:
  mov     w3, 0xbf
  adr     x6, display_file
  ret

po_mosaic_half_0xbf_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xbf_effects_regs:
  mov     w3, #0x2f
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xc0_setup_regs:
  mov     w3, 0xc0
  adr     x6, display_file
  ret

po_mosaic_half_0xc0_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xc0_effects_regs:
  mov     w3, #0x30
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xc1_setup_regs:
  mov     w3, 0xc1
  adr     x6, display_file
  ret

po_mosaic_half_0xc1_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xc1_effects_regs:
  mov     w3, #0x30
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xc2_setup_regs:
  mov     w3, 0xc2
  adr     x6, display_file
  ret

po_mosaic_half_0xc2_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xc2_effects_regs:
  mov     w3, #0x30
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xc3_setup_regs:
  mov     w3, 0xc3
  adr     x6, display_file
  ret

po_mosaic_half_0xc3_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xc3_effects_regs:
  mov     w3, #0x30
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xc4_setup_regs:
  mov     w3, 0xc4
  adr     x6, display_file
  ret

po_mosaic_half_0xc4_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xc4_effects_regs:
  mov     w3, #0x31
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xc5_setup_regs:
  mov     w3, 0xc5
  adr     x6, display_file
  ret

po_mosaic_half_0xc5_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xc5_effects_regs:
  mov     w3, #0x31
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xc6_setup_regs:
  mov     w3, 0xc6
  adr     x6, display_file
  ret

po_mosaic_half_0xc6_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xc6_effects_regs:
  mov     w3, #0x31
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xc7_setup_regs:
  mov     w3, 0xc7
  adr     x6, display_file
  ret

po_mosaic_half_0xc7_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xc7_effects_regs:
  mov     w3, #0x31
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xc8_setup_regs:
  mov     w3, 0xc8
  adr     x6, display_file
  ret

po_mosaic_half_0xc8_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xc8_effects_regs:
  mov     w3, #0x32
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xc9_setup_regs:
  mov     w3, 0xc9
  adr     x6, display_file
  ret

po_mosaic_half_0xc9_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xc9_effects_regs:
  mov     w3, #0x32
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xca_setup_regs:
  mov     w3, 0xca
  adr     x6, display_file
  ret

po_mosaic_half_0xca_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xca_effects_regs:
  mov     w3, #0x32
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xcb_setup_regs:
  mov     w3, 0xcb
  adr     x6, display_file
  ret

po_mosaic_half_0xcb_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xcb_effects_regs:
  mov     w3, #0x32
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xcc_setup_regs:
  mov     w3, 0xcc
  adr     x6, display_file
  ret

po_mosaic_half_0xcc_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xcc_effects_regs:
  mov     w3, #0x33
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xcd_setup_regs:
  mov     w3, 0xcd
  adr     x6, display_file
  ret

po_mosaic_half_0xcd_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xcd_effects_regs:
  mov     w3, #0x33
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xce_setup_regs:
  mov     w3, 0xce
  adr     x6, display_file
  ret

po_mosaic_half_0xce_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xce_effects_regs:
  mov     w3, #0x33
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xcf_setup_regs:
  mov     w3, 0xcf
  adr     x6, display_file
  ret

po_mosaic_half_0xcf_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xcf_effects_regs:
  mov     w3, #0x33
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xd0_setup_regs:
  mov     w3, 0xd0
  adr     x6, display_file
  ret

po_mosaic_half_0xd0_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xd0_effects_regs:
  mov     w3, #0x34
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xd1_setup_regs:
  mov     w3, 0xd1
  adr     x6, display_file
  ret

po_mosaic_half_0xd1_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xd1_effects_regs:
  mov     w3, #0x34
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xd2_setup_regs:
  mov     w3, 0xd2
  adr     x6, display_file
  ret

po_mosaic_half_0xd2_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xd2_effects_regs:
  mov     w3, #0x34
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xd3_setup_regs:
  mov     w3, 0xd3
  adr     x6, display_file
  ret

po_mosaic_half_0xd3_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xd3_effects_regs:
  mov     w3, #0x34
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xd4_setup_regs:
  mov     w3, 0xd4
  adr     x6, display_file
  ret

po_mosaic_half_0xd4_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xd4_effects_regs:
  mov     w3, #0x35
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xd5_setup_regs:
  mov     w3, 0xd5
  adr     x6, display_file
  ret

po_mosaic_half_0xd5_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xd5_effects_regs:
  mov     w3, #0x35
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xd6_setup_regs:
  mov     w3, 0xd6
  adr     x6, display_file
  ret

po_mosaic_half_0xd6_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xd6_effects_regs:
  mov     w3, #0x35
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xd7_setup_regs:
  mov     w3, 0xd7
  adr     x6, display_file
  ret

po_mosaic_half_0xd7_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xd7_effects_regs:
  mov     w3, #0x35
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xd8_setup_regs:
  mov     w3, 0xd8
  adr     x6, display_file
  ret

po_mosaic_half_0xd8_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xd8_effects_regs:
  mov     w3, #0x36
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xd9_setup_regs:
  mov     w3, 0xd9
  adr     x6, display_file
  ret

po_mosaic_half_0xd9_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xd9_effects_regs:
  mov     w3, #0x36
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xda_setup_regs:
  mov     w3, 0xda
  adr     x6, display_file
  ret

po_mosaic_half_0xda_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xda_effects_regs:
  mov     w3, #0x36
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xdb_setup_regs:
  mov     w3, 0xdb
  adr     x6, display_file
  ret

po_mosaic_half_0xdb_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xdb_effects_regs:
  mov     w3, #0x36
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xdc_setup_regs:
  mov     w3, 0xdc
  adr     x6, display_file
  ret

po_mosaic_half_0xdc_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xdc_effects_regs:
  mov     w3, #0x37
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xdd_setup_regs:
  mov     w3, 0xdd
  adr     x6, display_file
  ret

po_mosaic_half_0xdd_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xdd_effects_regs:
  mov     w3, #0x37
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xde_setup_regs:
  mov     w3, 0xde
  adr     x6, display_file
  ret

po_mosaic_half_0xde_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xde_effects_regs:
  mov     w3, #0x37
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xdf_setup_regs:
  mov     w3, 0xdf
  adr     x6, display_file
  ret

po_mosaic_half_0xdf_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xdf_effects_regs:
  mov     w3, #0x37
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xe0_setup_regs:
  mov     w3, 0xe0
  adr     x6, display_file
  ret

po_mosaic_half_0xe0_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xe0_effects_regs:
  mov     w3, #0x38
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xe1_setup_regs:
  mov     w3, 0xe1
  adr     x6, display_file
  ret

po_mosaic_half_0xe1_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xe1_effects_regs:
  mov     w3, #0x38
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xe2_setup_regs:
  mov     w3, 0xe2
  adr     x6, display_file
  ret

po_mosaic_half_0xe2_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xe2_effects_regs:
  mov     w3, #0x38
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xe3_setup_regs:
  mov     w3, 0xe3
  adr     x6, display_file
  ret

po_mosaic_half_0xe3_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xe3_effects_regs:
  mov     w3, #0x38
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xe4_setup_regs:
  mov     w3, 0xe4
  adr     x6, display_file
  ret

po_mosaic_half_0xe4_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xe4_effects_regs:
  mov     w3, #0x39
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xe5_setup_regs:
  mov     w3, 0xe5
  adr     x6, display_file
  ret

po_mosaic_half_0xe5_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xe5_effects_regs:
  mov     w3, #0x39
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xe6_setup_regs:
  mov     w3, 0xe6
  adr     x6, display_file
  ret

po_mosaic_half_0xe6_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xe6_effects_regs:
  mov     w3, #0x39
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xe7_setup_regs:
  mov     w3, 0xe7
  adr     x6, display_file
  ret

po_mosaic_half_0xe7_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xe7_effects_regs:
  mov     w3, #0x39
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xe8_setup_regs:
  mov     w3, 0xe8
  adr     x6, display_file
  ret

po_mosaic_half_0xe8_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xe8_effects_regs:
  mov     w3, #0x3a
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xe9_setup_regs:
  mov     w3, 0xe9
  adr     x6, display_file
  ret

po_mosaic_half_0xe9_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xe9_effects_regs:
  mov     w3, #0x3a
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xea_setup_regs:
  mov     w3, 0xea
  adr     x6, display_file
  ret

po_mosaic_half_0xea_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xea_effects_regs:
  mov     w3, #0x3a
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xeb_setup_regs:
  mov     w3, 0xeb
  adr     x6, display_file
  ret

po_mosaic_half_0xeb_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xeb_effects_regs:
  mov     w3, #0x3a
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xec_setup_regs:
  mov     w3, 0xec
  adr     x6, display_file
  ret

po_mosaic_half_0xec_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xec_effects_regs:
  mov     w3, #0x3b
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xed_setup_regs:
  mov     w3, 0xed
  adr     x6, display_file
  ret

po_mosaic_half_0xed_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xed_effects_regs:
  mov     w3, #0x3b
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xee_setup_regs:
  mov     w3, 0xee
  adr     x6, display_file
  ret

po_mosaic_half_0xee_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xee_effects_regs:
  mov     w3, #0x3b
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xef_setup_regs:
  mov     w3, 0xef
  adr     x6, display_file
  ret

po_mosaic_half_0xef_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xef_effects_regs:
  mov     w3, #0x3b
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xf0_setup_regs:
  mov     w3, 0xf0
  adr     x6, display_file
  ret

po_mosaic_half_0xf0_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xf0_effects_regs:
  mov     w3, #0x3c
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xf1_setup_regs:
  mov     w3, 0xf1
  adr     x6, display_file
  ret

po_mosaic_half_0xf1_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xf1_effects_regs:
  mov     w3, #0x3c
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xf2_setup_regs:
  mov     w3, 0xf2
  adr     x6, display_file
  ret

po_mosaic_half_0xf2_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xf2_effects_regs:
  mov     w3, #0x3c
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xf3_setup_regs:
  mov     w3, 0xf3
  adr     x6, display_file
  ret

po_mosaic_half_0xf3_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xf3_effects_regs:
  mov     w3, #0x3c
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xf4_setup_regs:
  mov     w3, 0xf4
  adr     x6, display_file
  ret

po_mosaic_half_0xf4_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xf4_effects_regs:
  mov     w3, #0x3d
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xf5_setup_regs:
  mov     w3, 0xf5
  adr     x6, display_file
  ret

po_mosaic_half_0xf5_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xf5_effects_regs:
  mov     w3, #0x3d
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xf6_setup_regs:
  mov     w3, 0xf6
  adr     x6, display_file
  ret

po_mosaic_half_0xf6_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xf6_effects_regs:
  mov     w3, #0x3d
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xf7_setup_regs:
  mov     w3, 0xf7
  adr     x6, display_file
  ret

po_mosaic_half_0xf7_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xf7_effects_regs:
  mov     w3, #0x3d
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xf8_setup_regs:
  mov     w3, 0xf8
  adr     x6, display_file
  ret

po_mosaic_half_0xf8_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xf8_effects_regs:
  mov     w3, #0x3e
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xf9_setup_regs:
  mov     w3, 0xf9
  adr     x6, display_file
  ret

po_mosaic_half_0xf9_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xf9_effects_regs:
  mov     w3, #0x3e
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xfa_setup_regs:
  mov     w3, 0xfa
  adr     x6, display_file
  ret

po_mosaic_half_0xfa_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xfa_effects_regs:
  mov     w3, #0x3e
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xfb_setup_regs:
  mov     w3, 0xfb
  adr     x6, display_file
  ret

po_mosaic_half_0xfb_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xfb_effects_regs:
  mov     w3, #0x3e
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xfc_setup_regs:
  mov     w3, 0xfc
  adr     x6, display_file
  ret

po_mosaic_half_0xfc_effects:
  _str    0x0000000000000000, display_file
  _str    0x0000000000000000, display_file+8
  ret

po_mosaic_half_0xfc_effects_regs:
  mov     w3, #0x3f
  mov     x4, #0x0000000000000000
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xfd_setup_regs:
  mov     w3, 0xfd
  adr     x6, display_file
  ret

po_mosaic_half_0xfd_effects:
  _str    0x00ff00ff00ff00ff, display_file
  _str    0x00ff00ff00ff00ff, display_file+8
  ret

po_mosaic_half_0xfd_effects_regs:
  mov     w3, #0x3f
  mov     x4, #0x00ff00ff00ff00ff
  mov     x5, #0x0000000000000000
  adr     x6, display_file+0x10
  nzcv    #0b0100
  ret

po_mosaic_half_0xfe_setup_regs:
  mov     w3, 0xfe
  adr     x6, display_file
  ret

po_mosaic_half_0xfe_effects:
  _str    0xff00ff00ff00ff00, display_file
  _str    0xff00ff00ff00ff00, display_file+8
  ret

po_mosaic_half_0xfe_effects_regs:
  mov     w3, #0x3f
  mov     x4, #0xff00ff00ff00ff00
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret

po_mosaic_half_0xff_setup_regs:
  mov     w3, 0xff
  adr     x6, display_file
  ret

po_mosaic_half_0xff_effects:
  _str    0xffffffffffffffff, display_file
  _str    0xffffffffffffffff, display_file+8
  ret

po_mosaic_half_0xff_effects_regs:
  mov     w3, #0x3f
  mov     x4, #0xffffffffffffffff
  mov     x5, #0xff00ff00ff00ff00
  adr     x6, display_file+0x10
  nzcv    #0b0000
  ret
