#!/usr/bin/env bash

# This file is part of the Spectrum +4 Project.
# Licencing information can be found in the LICENCE file
# (C) 2021-2026 Spectrum +4 Authors. All rights reserved.

set -eu
set -o pipefail
export SHELLOPTS

cd "$(dirname "${0}")"

# Extract sysvar definitions from bss.s. Labels and .space directives are on
# separate lines (due to label splitting). Only include entries with a //
# comment on the .space line (excludes internal padding like next_interrupt).
SYSVARS="$(
  name=""
  sed -n '/sysvars:/,/sysvars_end:/p' ../roms/bss.s | sed 's/^\/\/.*//' | while IFS= read -r line; do
    case "$line" in
      [A-Za-z_]*:) name="${line%:}" ;;
      *".space"*"//"*) echo "$name $(echo "$line" | sed 's/.*\.space *//; s/ .*//')" ;;
    esac
  done
)"
SYSVAR_COUNT=$(echo "${SYSVARS}" | wc -l | tr -d ' ')

echo "// This file is part of the Spectrum +4 Project.
// Licencing information can be found in the LICENCE file
// (C) 2021-$(date +%Y) Spectrum +4 Authors. All rights reserved.


// This file is auto-generated by ${0##*/}." 'DO NOT EDIT!'"


.set SYSVAR_COUNT, ${SYSVAR_COUNT}


.align 3
.text
sysvars_meta:" | sed 's/^  //'
echo "${SYSVARS}" | while read sysvar size; do
  echo "  .quad sysvar_${sysvar}"
done

echo "${SYSVARS}" | while read sysvar size; do
  echo
  echo
  echo ".align 3"
  echo "sysvar_${sysvar}:"
  echo "  .quad ${sysvar}-sysvars"
  echo "  .byte ${size}"
  echo "  .asciz \"${sysvar}\""
done
