# This file is part of the Spectrum +4 Project.
# Licencing information can be found in the LICENCE file
# (C) 2021 Spectrum +4 Authors. All rights reserved.

name: build/test Spectrum +4
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build and test spectrum4
        run: ./tup-under-docker.sh
      - name: ensure no local file changes present
        run: git status && test $(git status --porcelain | wc -l) == 0
