name: Docker images
on:
  push:
    branches:    
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    # for some unfathomable reason, the multiarch docker image building in
    # github actions takes an age 3 hours wasn't enough, trying 12 hours.
    # default timeout is 6 hours, but at some point we'll hit that.
    timeout-minutes: 720
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build/push docker images
        run: dev-setup/docker/build.sh
