name: Docker images
on:
  push:
    branches:    
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build/push docker images
        run: dev-setup/docker/build.sh
		# for some unfathomable reason, the multiarch docker image building in
		# github actions takes an age 3 hours wasn't enough, trying 12 hours.
		# default timeout is 6 hours, but at some point we'll hit that.
        timeout-minutes: 720
